import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { supabase } from "../src/lib/supabase";

type Tab="dashboard"|"professionals"|"verification"|"customers"|"services"|"jobs"|"payments"|"notifications"|"complaints"|"portfolio"|"audit";
const tabs:Tab[]=["dashboard","professionals","verification","customers","services","jobs","payments","notifications","complaints","portfolio","audit"];

export default function AdminScreen(){
 const[session,setSession]=useState<any>(null),[admin,setAdmin]=useState(false),[loading,setLoading]=useState(true);
 const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[message,setMessage]=useState("");
 const[tab,setTab]=useState<Tab>("dashboard");
 const[data,setData]=useState<any>({pros:[],verification:[],customers:[],services:[],jobs:[],payments:[],notifications:[],complaints:[],portfolio:[],audit:[]});

 useEffect(()=>{let mounted=true;
  supabase.auth.getSession().then(async({data:d})=>{if(!mounted)return;setSession(d.session);if(d.session)await checkAdmin();setLoading(false)});
  const {data:l}=supabase.auth.onAuthStateChange(async(_e,s)=>{setSession(s);if(s)await checkAdmin();else setAdmin(false);setLoading(false)});
  return()=>{mounted=false;l.subscription.unsubscribe()};
 },[]);

 async function checkAdmin(){const{data,error}=await supabase.rpc("is_admin");if(error){setAdmin(false);setMessage(error.message);return}setAdmin(Boolean(data));if(data)await loadAll()}
 async function login(){setMessage("");setLoading(true);const{error}=await supabase.auth.signInWithPassword({email,password});if(error)setMessage(error.message);else await checkAdmin();setLoading(false)}
 async function loadAll(){
  const calls:[string,string][]=[["pros","admin_marketplace_professionals"],["verification","admin_pending_verifications"],["customers","admin_customer_reputation"],["services","admin_marketplace_skills"],["jobs","admin_jobs"],["payments","admin_payment_orders"],["notifications","admin_notifications"],["complaints","admin_complaints"],["portfolio","admin_portfolio_moderation"],["audit","admin_audit_log"]];
  const results=await Promise.all(calls.map(async([key,fn])=>{const{data,error}=await supabase.rpc(fn);return[key,error?[]:data||[]]}));
  setData(Object.fromEntries(results));
 }
 async function signOut(){await supabase.auth.signOut();setAdmin(false);setSession(null)}
 async function act(fn:string,args:any,success:string,refresh=loadAll){setMessage("");const{error}=await supabase.rpc(fn,args);if(error){setMessage(error.message);return}setMessage(success);await refresh();}
 async function verify(id:string,decision:"approved"|"rejected"){const note=decision==="rejected"?window.prompt("Reason for rejection (optional):")||null:null;await act("admin_review_verification",{p_document_id:id,p_decision:decision,p_note:note},decision==="approved"?"Professional approved.":"Professional rejected.");}
 async function proStatus(id:string,status:"active"|"suspended"){await act("admin_set_professional_status",{p_user_id:id,p_status:status},status==="active"?"Professional activated.":"Professional suspended.",loadPros);}
 async function proAvailability(id:string,available:boolean){await act("admin_set_professional_availability",{p_user_id:id,p_available:available},available?"Professional made available.":"Professional made unavailable.",loadPros);}
 async function serviceStatus(id:string,active:boolean){await act("admin_set_skill_status",{p_skill_id:id,p_active:active},active?"Service activated.":"Service deactivated.",loadServices);}
 async function portfolioReview(id:string,decision:"approved"|"rejected"){const note=window.prompt(decision==="rejected"?"Reason for rejection (optional):":"Admin note (optional):")||null;await act("admin_review_portfolio",{p_portfolio_id:id,p_decision:decision,p_note:note},"Portfolio updated.",loadPortfolio);}
 async function complaintReview(id:string,status:string){const note=window.prompt("Admin note (optional):")||null;await act("admin_review_complaint",{p_complaint_id:id,p_status:status,p_note:note},"Complaint updated.",loadComplaints);}
 async function loadPros(){const{data,error}=await supabase.rpc("admin_marketplace_professionals");if(error)setMessage(error.message);else setData((v:any)=>({...v,pros:data||[]}))}
 async function loadServices(){const{data,error}=await supabase.rpc("admin_marketplace_skills");if(error)setMessage(error.message);else setData((v:any)=>({...v,services:data||[]}))}
 async function loadPortfolio(){const{data,error}=await supabase.rpc("admin_portfolio_moderation");if(error)setMessage(error.message);else setData((v:any)=>({...v,portfolio:data||[]}))}
 async function loadComplaints(){const{data,error}=await supabase.rpc("admin_complaints");if(error)setMessage(error.message);else setData((v:any)=>({...v,complaints:data||[]}))}

 if(loading)return <View style={s.center}><ActivityIndicator/><Text style={s.muted}>Loading admin console…</Text></View>;
 if(!session)return <View style={s.center}><View style={s.login}><Text style={s.logo}>VASUDHA CONNECT</Text><Text style={s.title}>Admin Console</Text><Text style={s.muted}>Authorized administrators only.</Text><TextInput style={s.input} autoCapitalize="none" keyboardType="email-address" placeholder="Admin email" value={email} onChangeText={setEmail}/><TextInput style={s.input} secureTextEntry placeholder="Password" value={password} onChangeText={setPassword}/><Pressable style={s.primary} onPress={login}><Text style={s.primaryText}>Sign in to Admin</Text></Pressable>{message?<Text style={s.error}>{message}</Text>:null}</View></View>;
 if(!admin)return <View style={s.center}><View style={s.login}><Text style={s.title}>Admin access required</Text><Text style={s.muted}>This account is not on the VASUDHA admin allow-list.</Text><Pressable style={s.secondary} onPress={signOut}><Text>Sign out</Text></Pressable>{message?<Text style={s.error}>{message}</Text>:null}</View></View>;

 const counts={verified:data.pros.filter((x:any)=>x.verification_status==="verified").length,pending:data.verification.length,customers:data.customers.length,jobs:data.jobs.length,paid:data.payments.filter((x:any)=>x.status==="paid").length,complaints:data.complaints.filter((x:any)=>["open","under_review"].includes(x.status)).length,portfolio:data.portfolio.filter((x:any)=>x.moderation_status==="pending").length,services:data.services.filter((x:any)=>x.is_active).length};
 return <View style={s.page}>
  <View style={s.header}><View><Text style={s.logo}>VASUDHA CONNECT</Text><Text style={s.title}>Admin Console</Text></View><Pressable onPress={signOut} style={s.secondary}><Text>Sign out</Text></Pressable></View>
  <View style={s.navWrap}><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.tabs}>{tabs.map(x=><Pressable key={x} onPress={()=>setTab(x)} style={tab===x?s.tabActive:s.tab}><Text style={tab===x?s.tabTextActive:s.tabText}>{x==="dashboard"?"Dashboard":x[0].toUpperCase()+x.slice(1)}</Text></Pressable>)}</ScrollView></View>
  <ScrollView style={s.body} contentContainerStyle={s.bodyInner}>
   {tab==="dashboard"&&<><View style={s.grid}>{Object.entries({Verified:counts.verified,Pending:counts.pending,Customers:counts.customers,Jobs:counts.jobs,Paid:counts.paid,"Open complaints":counts.complaints,"Portfolio pending":counts.portfolio,"Active services":counts.services}).map(([k,v])=><View key={k} style={s.metric}><Text style={s.muted}>{k}</Text><Text style={s.metricValue}>{String(v)}</Text></View>)}</View><Section title="Admin workflow"><Text style={s.muted}>Use the sections above to manage marketplace operations. State-changing actions remain protected by admin-only RPCs.</Text></Section></>}
   {tab==="professionals"&&<Section title="Professionals">{!data.pros.length?<Text style={s.muted}>No professionals found.</Text>:data.pros.map((x:any)=><View key={x.user_id} style={s.item}><View style={{flex:1}}><Text style={s.rowTitle}>{x.display_name||"Professional"}</Text><Text style={s.muted}>{x.headline||"No headline"} • Trust {Math.round(x.trust_score||0)}/100 • {x.verification_status}</Text></View><View style={s.actions}><Pressable style={s.secondary} onPress={()=>proAvailability(x.user_id,!x.is_available)}><Text>{x.is_available?"Make unavailable":"Make available"}</Text></Pressable><Pressable style={x.verification_status==="suspended"?s.primary:s.danger} onPress={()=>proStatus(x.user_id,x.verification_status==="suspended"?"active":"suspended")}><Text style={x.verification_status==="suspended"?s.primaryText:s.dangerText}>{x.verification_status==="suspended"?"Activate":"Suspend"}</Text></Pressable></View></View>)}</Section>}
   {tab==="verification"&&<Section title="Pending verification">{!data.verification.length?<Text style={s.muted}>No pending verification requests.</Text>:data.verification.map((x:any)=><View key={x.document_id} style={s.item}><View style={{flex:1}}><Text style={s.rowTitle}>{x.professional_name||"Professional"}</Text><Text style={s.muted}>{x.document_type||"Document"} • {x.city||""} {x.state||""}</Text></View><View style={s.actions}><Pressable style={s.secondary} onPress={()=>verify(x.document_id,"approved")}><Text>Approve</Text></Pressable><Pressable style={s.danger} onPress={()=>verify(x.document_id,"rejected")}><Text style={s.dangerText}>Reject</Text></Pressable></View></View>)}</Section>}
   {tab==="customers"&&<List title="Customers" items={data.customers} render={(x:any)=><Row title={x.display_name||"Customer"} subtitle={(x.city||"")+" "+(x.state||"")} meta={"Trust "+Math.round(x.customer_trust_score||0)+"/100 • "+(x.jobs_completed||0)+" jobs"}/>} />}
   {tab==="services"&&<Section title="Service catalogue">{!data.services.length?<Text style={s.muted}>No services found.</Text>:data.services.map((x:any)=><View key={x.id} style={s.item}><View style={{flex:1}}><Text style={s.rowTitle}>{x.name||"Service"}</Text><Text style={s.muted}>{x.category||""} • {x.professional_count||0} professionals • {x.is_active?"Active":"Inactive"}</Text></View><Pressable style={x.is_active?s.danger:s.primary} onPress={()=>serviceStatus(x.id,!x.is_active)}><Text style={x.is_active?s.dangerText:s.primaryText}>{x.is_active?"Deactivate":"Activate"}</Text></Pressable></View>)}</Section>}
   {tab==="jobs"&&<List title="Jobs & Work" items={data.jobs} render={(x:any)=><Row title={x.title||"Work"} subtitle={(x.customer_name||"Customer")+" → "+(x.professional_name||"Professional")} meta={(x.status||"")+" • ₹"+Number(x.agreed_amount_inr||0).toLocaleString("en-IN")}/>} />}
   {tab==="payments"&&<List title="Payments" items={data.payments} render={(x:any)=><Row title={(x.customer_name||"Customer")+" • "+(x.package_code||"Package")} subtitle={"₹"+Number(x.amount_inr||0).toLocaleString("en-IN")} meta={x.status||"unknown"}/>} />}
   {tab==="notifications"&&<List title="Notifications" items={data.notifications} render={(x:any)=><Row title={x.title||"Notification"} subtitle={(x.user_name||"User")+" • "+(x.type||"notification")} meta={x.push_sent_at?"Sent":x.push_error?"Failed":"Pending"}/>} />}
   {tab==="complaints"&&<Section title="Complaints & disputes">{!data.complaints.length?<Text style={s.muted}>No complaints found.</Text>:data.complaints.map((x:any)=><View key={x.id} style={s.item}><View style={{flex:1}}><Text style={s.rowTitle}>{(x.category||"Complaint").replaceAll("_"," ")}</Text><Text style={s.muted}>{x.reporter_name||"User"} reported {x.against_name||"User"} • {x.status||"open"}</Text></View>{x.status!=="resolved"&&<Pressable style={s.primary} onPress={()=>complaintReview(x.id,"resolved")}><Text style={s.primaryText}>Resolve</Text></Pressable>}</View>)}</Section>}
   {tab==="portfolio"&&<Section title="Portfolio moderation">{!data.portfolio.length?<Text style={s.muted}>No portfolio items found.</Text>:data.portfolio.map((x:any)=><View key={x.id} style={s.item}><View style={{flex:1}}><Text style={s.rowTitle}>{x.title||"Portfolio item"}</Text><Text style={s.muted}>{x.professional_name||"Professional"} • {x.moderation_status||"pending"}</Text></View>{x.moderation_status==="pending"&&<View style={s.actions}><Pressable style={s.primary} onPress={()=>portfolioReview(x.id,"approved")}><Text style={s.primaryText}>Approve</Text></Pressable><Pressable style={s.danger} onPress={()=>portfolioReview(x.id,"rejected")}><Text style={s.dangerText}>Reject</Text></Pressable></View>}</View>)}</Section>}
   {tab==="audit"&&<List title="Audit logs" items={data.audit} render={(x:any)=><Row title={(x.action||"action")+" • "+(x.entity_type||"entity")} subtitle={x.actor_name||"Admin"} meta={new Date(x.created_at).toLocaleString()}/>} />}
  </ScrollView>
 </View>
}

function Section({title,children}:{title:string;children:any}){return <View style={s.section}><Text style={s.sectionTitle}>{title}</Text>{children}</View>}
function List({title,items,render}:{title:string;items:any[];render:(x:any)=>any}){return <Section title={title}>{!items.length?<Text style={s.muted}>No records found.</Text>:items.map((x:any)=><View key={x.id||x.user_id||x.document_id}>{render(x)}</View>)}</Section>}
function Row({title,subtitle,meta}:{title:string;subtitle:string;meta:string}){return <View style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>{title}</Text><Text style={s.muted}>{subtitle}</Text></View><Text style={s.badge}>{meta}</Text></View>}

const s=StyleSheet.create({
 page:{flex:1,backgroundColor:"#f5f7f6"},center:{flex:1,justifyContent:"center",alignItems:"center",padding:24,backgroundColor:"#f5f7f6"},login:{width:"100%",maxWidth:440,backgroundColor:"#fff",padding:28,borderRadius:18},logo:{fontSize:18,fontWeight:"800",color:"#087f68",letterSpacing:1},title:{fontSize:28,fontWeight:"800",marginTop:6,marginBottom:8},muted:{color:"#66706d",fontSize:14},input:{borderWidth:1,borderColor:"#d9dfdc",borderRadius:10,padding:13,marginTop:12,backgroundColor:"#fff"},primary:{backgroundColor:"#087f68",padding:14,borderRadius:10,alignItems:"center",marginTop:14},primaryText:{color:"#fff",fontWeight:"800"},secondary:{borderWidth:1,borderColor:"#d4dad7",backgroundColor:"#fff",paddingHorizontal:14,paddingVertical:10,borderRadius:10,alignItems:"center"},error:{color:"#b42318",marginTop:12},header:{width:"100%",boxSizing:"border-box",paddingHorizontal:28,paddingVertical:16,paddingTop:22,flexDirection:"row",justifyContent:"space-between",alignItems:"center",backgroundColor:"#fff",minHeight:82},navWrap:{width:"100%",backgroundColor:"#fff",borderTopWidth:1,borderTopColor:"#edf0ef",borderBottomWidth:1,borderBottomColor:"#edf0ef"},tabs:{paddingHorizontal:20,paddingVertical:9,gap:8,alignItems:"center",minHeight:56},tab:{paddingHorizontal:14,paddingVertical:10,borderRadius:10,borderWidth:1,borderColor:"#dde3e0",alignSelf:"center",height:40},tabActive:{paddingHorizontal:14,paddingVertical:10,borderRadius:10,backgroundColor:"#087f68",alignSelf:"center",height:40},tabText:{fontWeight:"700",color:"#37413e"},tabTextActive:{fontWeight:"800",color:"#fff"},body:{flex:1,width:"100%"},bodyInner:{paddingHorizontal:24,paddingTop:18,paddingBottom:40,width:"100%",boxSizing:"border-box",alignSelf:"stretch"},grid:{flexDirection:"row",flexWrap:"wrap",gap:12,width:"100%"},metric:{backgroundColor:"#fff",borderRadius:14,padding:16,width:"calc(25% - 9px)",minWidth:190,gap:6},metricValue:{fontSize:28,fontWeight:"800"},section:{backgroundColor:"#fff",borderRadius:16,padding:18,marginTop:14,width:"100%",boxSizing:"border-box"},item:{flexDirection:"row",alignItems:"center",gap:14,borderTopWidth:1,borderTopColor:"#edf0ef",paddingVertical:14},actions:{flexDirection:"row",gap:8,alignItems:"center"},danger:{borderWidth:1,borderColor:"#f0b4b0",backgroundColor:"#fff",paddingHorizontal:14,paddingVertical:10,borderRadius:10},dangerText:{color:"#b42318",fontWeight:"800"},sectionTitle:{fontSize:20,fontWeight:"800",marginBottom:12},row:{flexDirection:"row",alignItems:"center",gap:12,borderTopWidth:1,borderTopColor:"#edf0ef",paddingVertical:14},rowTitle:{fontSize:16,fontWeight:"800"},badge:{fontSize:12,fontWeight:"800",maxWidth:180,textAlign:"right"}
});
