import { useState } from "react";
import { Alert, KeyboardAvoidingView, Platform, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { supabase } from "../src/lib/supabase";
import { VasudhaLogo } from "../src/components/VasudhaLogo";
type Mode="customer"|"professional";
export default function AuthScreen(){
 const[signup,setSignup]=useState(false),[mode,setMode]=useState<Mode>("customer"),[name,setName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false);
 async function submit(){if(!email.trim()||!password)return Alert.alert("Required","Enter email and password.");if(signup&&!name.trim())return Alert.alert("Required","Enter your name.");setBusy(true);try{if(signup){const{data,error}=await supabase.auth.signUp({email:email.trim().toLowerCase(),password,options:{data:{full_name:name.trim(),display_name:name.trim(),initial_mode:mode}}});if(error)throw error;if(!data.session)Alert.alert("Check your email","Confirm your email, then return to sign in.");}else{const{error}=await supabase.auth.signInWithPassword({email:email.trim().toLowerCase(),password});if(error)throw error;}}catch(error){Alert.alert("Authentication failed",error instanceof Error?error.message:"Please try again.");}finally{setBusy(false);}}
 return <SafeAreaView style={s.safe}><KeyboardAvoidingView style={s.flex} behavior={Platform.OS==="ios"?"padding":"height"}><ScrollView contentContainerStyle={s.container} keyboardShouldPersistTaps="handled"><VasudhaLogo/><Text style={s.heading}>{signup?"Create your account":"Welcome back"}</Text>
 {signup&&<TextInput returnKeyType="next" style={s.input} placeholder="Full name" value={name} onChangeText={setName}/>}<TextInput returnKeyType="next" style={s.input} placeholder="Email" value={email} onChangeText={setEmail} autoCapitalize="none" autoCorrect={false} keyboardType="email-address"/><TextInput returnKeyType="done" onSubmitEditing={submit} style={s.input} placeholder="Password" value={password} onChangeText={setPassword} secureTextEntry/>
 {signup&&<><Text style={s.label}>How will you use VASUDHA CONNECT?</Text><View style={s.row}><Pressable onPress={()=>setMode("customer")} style={[s.mode,mode==="customer"&&s.selected]}><Text style={mode==="customer"&&s.selectedText}>Find a professional</Text></Pressable><Pressable onPress={()=>setMode("professional")} style={[s.mode,mode==="professional"&&s.selected]}><Text style={mode==="professional"&&s.selectedText}>Offer my skills</Text></Pressable></View></>}
 <Pressable disabled={busy} onPress={submit} style={[s.primary,busy&&s.disabled]}><Text style={s.primaryText}>{busy?"Please wait...":signup?"Create account":"Sign in"}</Text></Pressable><Pressable onPress={()=>setSignup(!signup)} style={s.secondary}><Text>{signup?"Already have an account? Sign in":"New to VASUDHA? Create account"}</Text></Pressable>
 </ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#fff"},flex:{flex:1},container:{flexGrow:1,justifyContent:"center",padding:24,paddingBottom:40},heading:{fontSize:26,fontWeight:"800",marginTop:30,marginBottom:18,color:"#13201c"},input:{borderWidth:1,borderColor:"#cfdad6",borderRadius:12,padding:14,marginBottom:12,minHeight:48,backgroundColor:"#fff"},label:{fontWeight:"700",marginTop:6,marginBottom:10},row:{gap:10,marginBottom:18},mode:{borderWidth:1,borderColor:"#cfdad6",borderRadius:12,padding:14,minHeight:48,justifyContent:"center"},selected:{borderWidth:2,borderColor:"#087D65",backgroundColor:"#E7F7F2"},selectedText:{fontWeight:"800",color:"#087D65"},primary:{borderRadius:12,padding:15,alignItems:"center",backgroundColor:"#087D65",minHeight:48,justifyContent:"center"},primaryText:{fontWeight:"800",color:"#fff"},secondary:{padding:15,alignItems:"center"},disabled:{opacity:.55}});