import { useState } from "react";
import { Alert, Pressable, SafeAreaView, StyleSheet, Text, TextInput, View } from "react-native";
import { supabase } from "../src/lib/supabase";
type Mode="customer"|"professional";
export default function AuthScreen(){
 const[signup,setSignup]=useState(false),[mode,setMode]=useState<Mode>("customer"),[name,setName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false);
 async function submit(){if(!email.trim()||!password)return Alert.alert("Required","Enter email and password.");if(signup&&!name.trim())return Alert.alert("Required","Enter your name.");setBusy(true);try{if(signup){const{data,error}=await supabase.auth.signUp({email:email.trim().toLowerCase(),password,options:{data:{full_name:name.trim(),display_name:name.trim(),initial_mode:mode}}});if(error)throw error;if(!data.session)Alert.alert("Check your email","Confirm your email, then return to sign in.");}else{const{error}=await supabase.auth.signInWithPassword({email:email.trim().toLowerCase(),password});if(error)throw error;}}catch(error){Alert.alert("Authentication failed",error instanceof Error?error.message:"Please try again.");}finally{setBusy(false);}}
 return <SafeAreaView style={s.safe}><View style={s.container}><Text style={s.brand}>VASUDHA CONNECT</Text><Text style={s.tagline}>Find Skills Around You</Text><Text style={s.heading}>{signup?"Create your account":"Welcome back"}</Text>
 {signup&&<TextInput style={s.input} placeholder="Full name" value={name} onChangeText={setName}/>}<TextInput style={s.input} placeholder="Email" value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address"/><TextInput style={s.input} placeholder="Password" value={password} onChangeText={setPassword} secureTextEntry/>
 {signup&&<><Text style={s.label}>How will you use VASUDHA CONNECT?</Text><View style={s.row}><Pressable onPress={()=>setMode("customer")} style={[s.mode,mode==="customer"&&s.selected]}><Text>Find a professional</Text></Pressable><Pressable onPress={()=>setMode("professional")} style={[s.mode,mode==="professional"&&s.selected]}><Text>Offer my skills</Text></Pressable></View></>}
 <Pressable disabled={busy} onPress={submit} style={s.primary}><Text style={s.primaryText}>{busy?"Please wait...":signup?"Create account":"Sign in"}</Text></Pressable><Pressable onPress={()=>setSignup(!signup)} style={s.secondary}><Text>{signup?"Already have an account? Sign in":"New to VASUDHA? Create account"}</Text></Pressable>
 </View></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1},container:{flex:1,justifyContent:"center",padding:24},brand:{fontSize:30,fontWeight:"800",textAlign:"center"},tagline:{textAlign:"center",marginTop:6,opacity:.65},heading:{fontSize:22,fontWeight:"700",marginTop:40,marginBottom:18},input:{borderWidth:1,borderColor:"#ccc",borderRadius:12,padding:14,marginBottom:12},label:{fontWeight:"600",marginTop:6,marginBottom:10},row:{gap:10,marginBottom:18},mode:{borderWidth:1,borderColor:"#ccc",borderRadius:12,padding:14},selected:{borderWidth:2},primary:{borderRadius:12,padding:15,alignItems:"center",borderWidth:1},primaryText:{fontWeight:"800"},secondary:{padding:15,alignItems:"center"}});
