import { useEffect, useState } from "react";
import { Alert, KeyboardAvoidingView, Platform, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useLocalSearchParams, router } from "expo-router";
import { supabase } from "../src/lib/supabase";
import { useAuth } from "../src/auth/AuthProvider";
import { VasudhaLogo } from "../src/components/VasudhaLogo";

export default function Chat(){
 const {conversationId,otherName,professionalId}=useLocalSearchParams<{conversationId:string;otherName:string}>();const {user}=useAuth();const [messages,setMessages]=useState<any[]>([]);const [body,setBody]=useState("");const [sending,setSending]=useState(false);const [loading,setLoading]=useState(true);
 useEffect(()=>{load();if(!conversationId)return;const ch=supabase.channel("chat-"+conversationId).on("postgres_changes",{event:"INSERT",schema:"public",table:"messages",filter:`conversation_id=eq.${conversationId}`},payload=>setMessages(prev=>prev.some(x=>x.id===payload.new.id)?prev:[...prev,payload.new])).subscribe();return()=>{supabase.removeChannel(ch);};},[conversationId]);
 async function load(){if(!conversationId){setLoading(false);return;}setLoading(true);const{data,error}=await supabase.from("messages").select("id,conversation_id,sender_id,body,created_at").eq("conversation_id",conversationId).order("created_at",{ascending:true});if(error)Alert.alert("Unable to load chat",error.message);else setMessages(data||[]);setLoading(false);}
 async function send(){const text=body.trim();if(!text||!conversationId||sending)return;setSending(true);const{data,error}=await supabase.rpc("send_message",{p_conversation_id:conversationId,p_body:text});setSending(false);if(error)Alert.alert("Message failed",error.message);else{setBody("");if(data)setMessages(prev=>prev.some(x=>x.id===data.id)?prev:[...prev,data]);}}
 return <SafeAreaView style={s.safe}><KeyboardAvoidingView style={s.flex} behavior={Platform.OS==="ios"?"padding":"height"}><View style={s.header}><Pressable onPress={()=>router.back()} style={s.back}><Text style={s.backText}>‹</Text></Pressable><VasudhaLogo compact/><View style={s.headerText}><Text style={s.title}>{otherName||"Ramesh Kumar"}</Text><Text style={s.muted}>Last seen recently</Text></View></View><ScrollView contentContainerStyle={s.messages} keyboardShouldPersistTaps="handled"><>{loading?<Text style={s.muted}>Loading messages…</Text>:messages.length===0?<Text style={s.muted}>Start the conversation.</Text>:messages.map(m=><View key={m.id} style={[s.bubble,m.sender_id===user?.id?s.mine:s.theirs]}><Text style={m.sender_id===user?.id?s.mineText:s.theirText}>{m.body}</Text><Text style={[s.time,m.sender_id===user?.id&&s.mineTime]}>{new Date(m.created_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</Text></View>)}</></ScrollView><View style={s.jobAction}><Pressable onPress={()=>router.push({pathname:"/service-request",params:{professionalId:professionalId||"",serviceId:"",subServiceId:""}})} style={s.jobButton}><Text style={s.jobButtonText}>Request Job</Text></Pressable><Text style={s.jobHint}>After you agree, send the job details here for professional acceptance.</Text></View><View style={s.composer}><TextInput value={body} onChangeText={setBody} placeholder="Write a message..." multiline returnKeyType="default" style={s.input}/><Pressable onPress={send} disabled={sending||!body.trim()} style={[s.send,(sending||!body.trim())&&s.sendDisabled]}><Text style={s.sendText}>{sending?"...":"Send"}</Text></Pressable></View></KeyboardAvoidingView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#fff"},flex:{flex:1},header:{padding:12,borderBottomWidth:1,borderBottomColor:"#e5ece9",flexDirection:"row",alignItems:"center",gap:10},back:{width:38,height:38,borderRadius:19,backgroundColor:"#f2f7f5",alignItems:"center",justifyContent:"center"},backText:{fontSize:28,color:"#13201c"},headerText:{flex:1},title:{fontSize:20,fontWeight:"800"},muted:{opacity:.6},messages:{padding:16,flexGrow:1,justifyContent:"flex-end"},bubble:{maxWidth:"82%",padding:12,borderRadius:15,marginBottom:10},mine:{alignSelf:"flex-end",backgroundColor:"#087D65"},theirs:{alignSelf:"flex-start",borderWidth:1,borderColor:"#e2e8e5",backgroundColor:"#fff"},mineText:{color:"#fff"},theirText:{color:"#13201c"},time:{fontSize:10,opacity:.5,marginTop:5},mineTime:{color:"#fff",opacity:.7},jobAction:{paddingHorizontal:12,paddingTop:8,backgroundColor:"#fbfdfc",borderTopWidth:1,borderTopColor:"#e5ece9"},jobButton:{alignSelf:"flex-start",borderRadius:10,backgroundColor:"#087D65",paddingHorizontal:14,paddingVertical:9},jobButtonText:{color:"#fff",fontWeight:"800"},jobHint:{fontSize:11,color:"#66736e",marginTop:5,marginBottom:5},composer:{flexDirection:"row",padding:10,borderTopWidth:1,borderTopColor:"#e5ece9",alignItems:"flex-end",backgroundColor:"#fff"},attach:{width:38,height:38,borderRadius:19,backgroundColor:"#f2f7f5",alignItems:"center",justifyContent:"center",marginRight:7},input:{flex:1,borderWidth:1,borderColor:"#cfdad6",borderRadius:12,padding:10,maxHeight:100,minHeight:44},send:{marginLeft:8,borderRadius:12,paddingHorizontal:15,paddingVertical:13,backgroundColor:"#087D65"},sendDisabled:{opacity:.45},sendText:{color:"#fff",fontWeight:"800"}});