import { useEffect, useState } from "react";
import { Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useLocalSearchParams } from "expo-router";
import { supabase } from "../src/lib/supabase";
import { useAuth } from "../src/context/AuthProvider";

export default function Chat(){
 const {conversationId,otherName}=useLocalSearchParams<{conversationId:string;otherName:string}>();
 const {user}=useAuth(); const [messages,setMessages]=useState<any[]>([]); const [body,setBody]=useState(""); const [sending,setSending]=useState(false);
 useEffect(()=>{load(); if(!conversationId)return; const ch=supabase.channel("chat-"+conversationId).on("postgres_changes",{event:"INSERT",schema:"public",table:"messages",filter:`conversation_id=eq.${conversationId}`},payload=>setMessages(prev=>prev.some(x=>x.id===payload.new.id)?prev:[...prev,payload.new])).subscribe(); return()=>{supabase.removeChannel(ch);};},[conversationId]);
 async function load(){if(!conversationId)return;const {data,error}=await supabase.from("messages").select("id,conversation_id,sender_id,body,created_at").eq("conversation_id",conversationId).order("created_at",{ascending:true});if(error)Alert.alert("Unable to load chat",error.message);else setMessages(data||[]);}
 async function send(){const text=body.trim();if(!text||!conversationId||sending)return;setSending(true);const {data,error}=await supabase.rpc("send_message",{p_conversation_id:conversationId,p_body:text});setSending(false);if(error)Alert.alert("Message failed",error.message);else{setBody("");setMessages(prev=>prev.some(x=>x.id===data.id)?prev:[...prev,data]);}}
 return <SafeAreaView style={s.safe}><View style={s.header}><Text style={s.title}>{otherName||"Chat"}</Text><Text style={s.muted}>VASUDHA CONNECT</Text></View><ScrollView contentContainerStyle={s.messages}>{messages.length===0?<Text style={s.muted}>Start the conversation.</Text>:messages.map(m=><View key={m.id} style={[s.bubble,m.sender_id===user?.id?s.mine:s.theirs]}><Text style={m.sender_id===user?.id?s.mineText:s.theirText}>{m.body}</Text><Text style={s.time}>{new Date(m.created_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</Text></View>)}</ScrollView><View style={s.composer}><TextInput value={body} onChangeText={setBody} placeholder="Write a message..." multiline style={s.input}/><Pressable onPress={send} disabled={sending||!body.trim()} style={s.send}><Text style={s.sendText}>{sending?"...":"Send"}</Text></Pressable></View></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1},header:{padding:18,borderBottomWidth:1},title:{fontSize:22,fontWeight:"800"},muted:{opacity:.6},messages:{padding:16,flexGrow:1},bubble:{maxWidth:"82%",padding:12,borderRadius:15,marginBottom:10},mine:{alignSelf:"flex-end",backgroundColor:"#111"},theirs:{alignSelf:"flex-start",borderWidth:1},mineText:{color:"#fff"},theirText:{color:"#111"},time:{fontSize:10,opacity:.5,marginTop:5},composer:{flexDirection:"row",padding:10,borderTopWidth:1,alignItems:"flex-end"},input:{flex:1,borderWidth:1,borderRadius:12,padding:10,maxHeight:100},send:{marginLeft:8,borderRadius:12,paddingHorizontal:15,paddingVertical:13,backgroundColor:"#111"},sendText:{color:"#fff",fontWeight:"800"}});