import{useEffect,useState}from"react";import{ActivityIndicator,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View}from"react-native";import{router}from"expo-router";import{supabase}from"../src/lib/supabase";import{useAuth}from"../src/auth/AuthProvider";import{VasudhaLogo}from"../src/components/VasudhaLogo";import{AppBottomNav}from"../src/components/AppBottomNav";
const labels:any={open:"Submitted",under_review:"Under review",upheld:"Upheld",dismissed:"Dismissed",resolved:"Resolved"};
export default function Complaints(){
 const{user,mode}=useAuth();const[items,setItems]=useState<any[]>([]);const[loading,setLoading]=useState(true);
 useEffect(()=>{load()},[user?.id]);
 async function load(){if(!user){setLoading(false);return}setLoading(true);const{data,error}=await supabase.from("complaints").select("id,job_id,reporter_id,against_user_id,category,description,status,admin_note,created_at,updated_at").or(`reporter_id.eq.${user.id},against_user_id.eq.${user.id}`).order("created_at",{ascending:false}).limit(50);if(!error)setItems(data||[]);setLoading(false)}
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.c}><View style={s.top}><VasudhaLogo compact/><Pressable onPress={load} style={s.refresh}><Text>↻</Text></Pressable></View><Text style={s.title}>Complaints & Reports</Text><Text style={s.sub}>{mode==="professional"?"Track reports involving your professional account.":"Track complaints you have submitted."}</Text>
 {loading?<View style={s.state}><ActivityIndicator color="#087D65"/><Text style={s.muted}>Loading complaint history…</Text></View>:!items.length?<View style={s.empty}><Text style={s.emptyTitle}>No complaints</Text><Text style={s.muted}>Your complaint history will appear here.</Text></View>:items.map(x=>{constmine=x.reporter_id===user?.id;return <View key={x.id} style={s.card}><View style={s.head}><Text style={s.category}>{String(x.category).replaceAll("_"," ")}</Text><Text style={s.badge}>{labels[x.status]||x.status}</Text></View><Text style={s.role}>{mine?"You reported this issue":"This report concerns your account"}</Text><Text style={s.desc}>{x.description}</Text><Text style={s.time}>{new Date(x.created_at).toLocaleString()} · Job {String(x.job_id).slice(0,8)}</Text>{x.admin_note?<View style={s.note}><Text style={s.noteTitle}>VASUDHA update</Text><Text style={s.noteText}>{x.admin_note}</Text></View>:null}</View>})}
 <Pressable style={s.secondary} onPress={()=>router.back()}><Text style={s.secondaryText}>Back</Text></Pressable>
 </ScrollView><AppBottomNav active="profile"/></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#fff"},c:{padding:20,paddingBottom:110},top:{height:46,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},refresh:{width:40,height:40,borderRadius:20,backgroundColor:"#f2f7f5",alignItems:"center",justifyContent:"center"},title:{fontSize:28,fontWeight:"900",color:"#13201c"},sub:{color:"#66736e",lineHeight:19,marginTop:5},card:{borderWidth:1,borderColor:"#e2e8e5",borderRadius:16,padding:15,marginTop:12},head:{flexDirection:"row",justifyContent:"space-between",gap:10,alignItems:"center"},category:{fontWeight:"900",fontSize:16,textTransform:"capitalize",flex:1},badge:{backgroundColor:"#eef6f3",color:"#087D65",fontWeight:"900",fontSize:11,paddingHorizontal:9,paddingVertical:5,borderRadius:10},role:{fontSize:11,color:"#66736e",marginTop:5},desc:{marginTop:8,lineHeight:18},time:{fontSize:11,color:"#66736e",marginTop:8},note:{marginTop:10,padding:10,borderRadius:10,backgroundColor:"#f5f8f7"},noteTitle:{fontWeight:"900",fontSize:11,color:"#087D65"},noteText:{fontSize:12,lineHeight:17,marginTop:3},empty:{borderWidth:1,borderColor:"#e2e8e5",borderRadius:16,padding:20,marginTop:20},emptyTitle:{fontSize:18,fontWeight:"900"},muted:{color:"#66736e",marginTop:5,lineHeight:18},state:{alignItems:"center",paddingVertical:40},secondary:{marginTop:18,borderWidth:1,borderColor:"#cfdad6",borderRadius:12,padding:13,alignItems:"center"},secondaryText:{fontWeight:"800",color:"#087D65"}});
