import{useEffect,useState}from"react";import{Alert,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View}from"react-native";import{useLocalSearchParams,router}from"expo-router";import{useAuth}from"../src/auth/AuthProvider";import{supabase}from"../src/lib/supabase";import{KAMPRO}from"../src/components/kamproTheme";
const cats=[["payment","Payment"],["quality","Work Quality"],["behaviour","Behaviour"],["safety","Safety"],["no_show","No-show"],["misrepresentation","Misrepresentation"],["property_damage","Property Damage"],["communication","Communication"],["other","Other"]];
const statusText:any={open:"Submitted",under_review:"Under review",upheld:"Upheld",dismissed:"Dismissed",resolved:"Resolved"};
export default function Complaint(){const{jobId,againstUserId}=useLocalSearchParams<{jobId:string;againstUserId:string}>();const{user}=useAuth();const[cat,setCat]=useState("");const[desc,setDesc]=useState("");const[evidence,setEvidence]=useState("");const[busy,setBusy]=useState(false);const[history,setHistory]=useState<any[]>([]);
 useEffect(()=>{loadHistory()},[user?.id]);
 async function loadHistory(){if(!user)return;const{data,error}=await supabase.from("complaints").select("id,job_id,category,description,status,admin_note,created_at,updated_at").eq("reporter_id",user.id).order("created_at",{ascending:false}).limit(30);if(!error)setHistory(data||[])}
 async function submit(){if(!jobId||!againstUserId||!cat||desc.trim().length<10){Alert.alert("Complete complaint","Choose a category and provide at least 10 characters describing the problem.");return}setBusy(true);const{error}=await supabase.from("complaints").insert({job_id:jobId,reporter_id:user?.id,against_user_id:againstUserId,category:cat,description:desc.trim(),evidence_note:evidence.trim()||null});setBusy(false);if(error)Alert.alert("Unable to submit",error.message);else{setCat("");setDesc("");setEvidence("");await loadHistory();Alert.alert("Complaint submitted","Your complaint has been added to your complaint history and is now awaiting review.")}}
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.c} keyboardShouldPersistTaps="handled"><View style={s.top}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹</Text></Pressable><Text style={s.topTitle}>KAMPRO</Text><View style={{width:24}}/></View>
 {jobId&&againstUserId?<><View style={s.warning}><Text style={s.warningIcon}>!</Text><Text style={s.warningText}>Report a problem with this job. Your complaint will be reviewed by our team.</Text></View><Text style={s.t}>Report a Problem</Text><Text style={s.m}>Report issues related to this job. Please provide factual details and useful evidence.</Text>
 <Text style={s.l}>Category</Text><View style={s.wrap}>{cats.map(([v,l])=><Pressable key={v} onPress={()=>setCat(v)} style={[s.chip,cat===v&&s.sel]}><Text style={cat===v?s.w:s.d}>{l}</Text></Pressable>)}</View>
 <Text style={s.l}>What happened?</Text><TextInput value={desc} onChangeText={setDesc} multiline placeholder="Describe the issue..." style={s.input}/><Text style={s.l}>Evidence / additional information (optional)</Text><TextInput value={evidence} onChangeText={setEvidence} multiline placeholder="Reference photos, receipts, messages, or other evidence..." style={s.input}/>
 <Pressable disabled={busy} onPress={submit} style={s.p}><Text style={s.w}>{busy?"Submitting...":"Submit Complaint"}</Text></Pressable></>:<><Text style={s.t}>Complaints & Reports</Text><Text style={s.m}>View your complaint history. To report a problem, open the relevant job and choose Report a Problem.</Text></>}
 <Text style={s.section}>My Complaint History</Text>{history.length===0?<Text style={s.empty}>No complaints submitted yet.</Text>:history.map(x=><View key={x.id} style={s.card}><View style={s.cardHead}><Text style={s.cardTitle}>{String(x.category).replaceAll("_"," ")}</Text><Text style={s.badge}>{statusText[x.status]||x.status}</Text></View><Text style={s.cardDesc}>{x.description}</Text><Text style={s.time}>{new Date(x.created_at).toLocaleString()} · Job {String(x.job_id).slice(0,8)}</Text>{x.admin_note?<View style={s.note}><Text style={s.noteTitle}>KAMPRO update</Text><Text style={s.noteText}>{x.admin_note}</Text></View>:null}</View>)}
 </ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:KAMPRO.background},c:{width:"100%",maxWidth:820,alignSelf:"center",padding:28,paddingBottom:60},top:{height:46,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},back:{fontSize:30,color:"#10233F"},topTitle:{fontWeight:"900",color:"#FF4B1F"},warning:{marginTop:12,backgroundColor:"#fff7df",borderRadius:12,padding:12,flexDirection:"row",gap:9},warningIcon:{width:22,height:22,borderRadius:11,backgroundColor:"#f0b429",color:"#fff",textAlign:"center",fontWeight:"900",paddingTop:1},warningText:{flex:1,color:"#6b5a2c",fontSize:12,lineHeight:17},t:{fontSize:28,fontWeight:"800",color:"#10233F"},m:{color:"#596575",marginTop:6,lineHeight:20},l:{fontWeight:"800",color:"#26364B",marginTop:20,marginBottom:8},wrap:{flexDirection:"row",flexWrap:"wrap",gap:8},chip:{borderWidth:1,borderColor:"#CBD0D8",borderRadius:18,paddingHorizontal:12,paddingVertical:9},sel:{backgroundColor:"#FF4B1F",borderColor:"#FF4B1F"},w:{color:"#fff",fontWeight:"800"},d:{color:"#111"},input:{borderWidth:1,borderColor:"#CBD0D8",borderRadius:12,padding:12,height:120,textAlignVertical:"top",color:"#172033",backgroundColor:"#FFFFFF"},p:{marginTop:24,borderRadius:12,padding:15,alignItems:"center",justifyContent:"center",minHeight:48,backgroundColor:"#FF4B1F"},section:{fontSize:21,fontWeight:"900",marginTop:30,color:"#10233F"},empty:{color:"#596575",marginTop:10},card:{borderWidth:1,borderColor:"#E7EAF0",borderRadius:15,padding:14,marginTop:12},cardHead:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",gap:10},cardTitle:{fontWeight:"900",fontSize:16,textTransform:"capitalize",flex:1,color:"#10233F"},badge:{backgroundColor:"#eef6f3",color:"#FF4B1F",fontWeight:"900",paddingHorizontal:9,paddingVertical:5,borderRadius:10,fontSize:11},cardDesc:{marginTop:8,lineHeight:18,color:"#26364B"},time:{fontSize:11,color:"#6B7280",marginTop:8},note:{marginTop:10,padding:10,borderRadius:10,backgroundColor:"#f5f8f7"},noteTitle:{fontWeight:"900",fontSize:11,color:"#FF4B1F"},noteText:{fontSize:12,marginTop:3,lineHeight:17}});
