import { useEffect, useState } from "react";
import { Link } from "expo-router";
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";
import { supabase } from "../src/lib/supabase";
type P={code:string;name:string;connections:number;price_inr:number;validity_days:number};
export default function ConnectionPackages(){
 const[packages,setPackages]=useState<P[]>([]),[balance,setBalance]=useState(0);
 useEffect(()=>{load();},[]);
 async function load(){const[{data:p},{data:b}]=await Promise.all([supabase.from("connection_packages").select("code,name,connections,price_inr,validity_days").eq("is_active",true).order("price_inr"),supabase.rpc("get_connection_balance")]);setPackages(p||[]);setBalance(b||0);}
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container}><Text style={s.title}>Connection Packages</Text><Text style={s.sub}>Unlock verified professionals and connect directly.</Text><View style={s.balance}><Text>Your available connections</Text><Text style={s.balanceValue}>{balance}</Text></View>{packages.map(p=><View key={p.code} style={s.card}><View style={s.row}><Text style={s.name}>{p.name}</Text><Text style={s.price}>₹{p.price_inr}</Text></View><Text>{p.connections} connections • {p.validity_days} days</Text><Text style={s.muted}>₹{(p.price_inr/p.connections).toFixed(2)} per connection</Text><Pressable disabled style={s.disabled}><Text style={s.disabledText}>Payment setup required</Text></Pressable></View>)}<Link href="/marketplace" asChild><Pressable style={s.back}><Text style={s.backText}>Back to professionals</Text></Pressable></Link><Text style={s.note}>Your connection credit is consumed only when you unlock a professional. Once unlocked, that professional remains accessible for 30 days.</Text></ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1},container:{padding:20,paddingBottom:50},title:{fontSize:28,fontWeight:"800"},sub:{marginTop:5,opacity:.65,marginBottom:18},balance:{borderWidth:1,borderRadius:16,padding:16,marginBottom:16},balanceValue:{fontSize:28,fontWeight:"800",marginTop:4},card:{borderWidth:1,borderRadius:16,padding:16,marginBottom:12},row:{flexDirection:"row",justifyContent:"space-between"},name:{fontSize:18,fontWeight:"800"},price:{fontSize:18,fontWeight:"800"},muted:{opacity:.6,marginTop:4},disabled:{marginTop:12,borderRadius:10,padding:12,alignItems:"center",backgroundColor:"#eee"},disabledText:{fontWeight:"700",opacity:.6},back:{borderWidth:1,borderRadius:12,padding:14,alignItems:"center",marginTop:8},backText:{fontWeight:"800"},note:{marginTop:18,opacity:.6,fontSize:12}});