import { useEffect,useState } from "react";
import { ActivityIndicator,Alert,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View } from "react-native";
import { router } from "expo-router";
import { supabase } from "../src/lib/supabase";
import { VasudhaLogo } from "../src/components/VasudhaLogo";
import { AppBottomNav } from "../src/components/AppBottomNav";
import { useAuth } from "../src/auth/AuthProvider";

export default function CustomerDashboard(){
 const {user}=useAuth();const [balance,setBalance]=useState(0);const [connections,setConnections]=useState<any[]>([]);const [requests,setRequests]=useState<any[]>([]);const [jobs,setJobs]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 useEffect(()=>{load();},[user?.id]);
 async function load(){if(!user)return;setLoading(true);setError("");const results=await Promise.all([
  supabase.from("professional_connections").select("id,professional_id,expires_at").eq("customer_id",user.id).gt("expires_at",new Date().toISOString()).order("expires_at",{ascending:true}),
  supabase.from("service_requests").select("id,title,description,status,professional_id,created_at").eq("customer_id",user.id).order("created_at",{ascending:false}).limit(20),
  supabase.from("jobs").select("id,title,agreed_amount_inr,status,professional_id,created_at").eq("customer_id",user.id).order("created_at",{ascending:false}).limit(20)
 ]);const {data:wallet}=await supabase.rpc("get_connection_balance");setBalance(wallet||0);const firstError=results.find(x=>x.error)?.error;if(firstError){setError(firstError.message);Alert.alert("Unable to load dashboard",firstError.message);}setConnections(results[0].data||[]);setRequests(results[1].data||[]);setJobs(results[2].data||[]);setLoading(false);}
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container} keyboardShouldPersistTaps="handled"><VasudhaLogo/><Text style={s.title}>Customer Dashboard</Text><Text style={s.subtitle}>Everything you're managing in VASUDHA CONNECT</Text>{loading?<View style={s.state}><ActivityIndicator/><Text style={s.muted}>Loading your dashboard…</Text></View>:error?<View style={s.state}><Text style={s.errorTitle}>Couldn't load your dashboard</Text><Text style={s.muted}>{error}</Text><Pressable onPress={load} style={s.secondary}><Text>Try again</Text></Pressable></View>:<><View style={s.stats}><View style={s.stat}><Text style={s.num}>{connections.length}</Text><Text>Connections</Text></View><View style={s.stat}><Text style={s.num}>{requests.length}</Text><Text>Requests</Text></View><View style={s.stat}><Text style={s.num}>{jobs.length}</Text><Text>Jobs</Text></View></View><Pressable onPress={()=>router.push("/marketplace")} style={s.primary}><Text style={s.primaryText}>Find Professionals</Text></Pressable><Pressable onPress={()=>router.push("/connection-packages")} style={s.secondary}><Text>Connection Wallet · {balance} unlocks left</Text></Pressable><Text style={s.section}>Service Requests</Text>{requests.length===0?<Text style={s.muted}>No service requests yet.</Text>:requests.map(r=><View key={r.id} style={s.card}><Text style={s.name}>{r.title}</Text><Text style={s.status}>{r.status}</Text><Text style={s.muted}>{r.status==="requested"?"Waiting for the professional to accept after discussion.":r.status==="accepted"?"Accepted · opening your job will show tracking and contact options.":"Job request in progress."}</Text>{r.status==="accepted"?<Pressable onPress={()=>{const j=jobs.find(x=>x.title===r.title&&x.professional_id===r.professional_id);if(j)router.push({pathname:"/job-details",params:{jobId:j.id}});else router.push("/jobs")}} style={s.secondary}><Text>Open Job</Text></Pressable>:null}</View>)}<Text style={s.section}>Active & Past Jobs</Text>{jobs.length===0?<Text style={s.muted}>No jobs yet.</Text>:jobs.map(j=><View key={j.id} style={s.card}><Text style={s.name}>{j.title}</Text><Text style={s.status}>{j.status}</Text><Pressable onPress={()=>router.push("/jobs")} style={s.secondary}><Text>Open Tracking</Text></Pressable></View>)}<Text style={s.section}>Connections</Text>{connections.length===0?<Text style={s.muted}>No active connections.</Text>:<Pressable onPress={()=>router.push("/connections")} style={s.secondary}><Text>Open My Connections & Chat</Text></Pressable>}</>}</ScrollView><AppBottomNav/></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#fff"},container:{padding:20,paddingBottom:34},title:{fontSize:28,fontWeight:"800",color:"#13201c"},subtitle:{opacity:.6,marginTop:5,lineHeight:19},stats:{flexDirection:"row",gap:10,marginTop:20},stat:{flex:1,borderWidth:1,borderColor:"#e2e8e5",borderRadius:14,padding:14,alignItems:"center",minHeight:78},num:{fontSize:22,fontWeight:"800",color:"#087D65"},primary:{marginTop:18,borderRadius:12,padding:14,alignItems:"center",backgroundColor:"#087D65",minHeight:48,justifyContent:"center"},primaryText:{color:"#fff",fontWeight:"800"},section:{fontSize:21,fontWeight:"800",marginTop:25,color:"#13201c"},card:{borderWidth:1,borderColor:"#e2e8e5",borderRadius:16,padding:16,marginTop:12},name:{fontSize:17,fontWeight:"800"},status:{fontWeight:"800",marginTop:8,color:"#087D65"},muted:{opacity:.6,marginTop:8,lineHeight:19},secondary:{marginTop:10,borderWidth:1,borderColor:"#cfdad6",borderRadius:12,padding:12,alignItems:"center",minHeight:44,justifyContent:"center"},state:{alignItems:"center",paddingVertical:40},errorTitle:{fontWeight:"800",fontSize:17,color:"#b42318"}});