import { useEffect, useState } from "react";
import { Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { VasudhaLogo } from "../src/components/VasudhaLogo";
import { useLocalSearchParams, router } from "expo-router";
import { supabase } from "../src/lib/supabase";

const fields=[["punctuality","Punctuality & Time"],["work_quality","Work Quality / Expertise"],["professional_behaviour","Professional Behaviour"],["communication","Communication"],["value_for_money","Price / Value for Money"],["reliability","Reliability"],["safety_care","Safety & Care"]];
export default function CustomerReview(){const {jobId,customerId}=useLocalSearchParams<{jobId:string;customerId:string}>();const[scores,setScores]=useState<Record<string,number>>({});const[again,setAgain]=useState(true);const[comment,setComment]=useState("");const[busy,setBusy]=useState(false);
async function submit(){if(!jobId||!customerId||fields.some(([k])=>!scores[k])){Alert.alert("Complete review","Please rate every category.");return;}setBusy(true);const{data:{user}}=await supabase.auth.getUser();const payload:any={job_id:jobId,customer_id:customerId,professional_id:user?.id,would_hire_again:again,comment:comment.trim()||null};fields.forEach(([k])=>payload[k]=scores[k]);const{error}=await supabase.from("customer_job_reviews").insert(payload);setBusy(false);if(error)Alert.alert("Review failed",error.message);else{Alert.alert("Thank you","Customer feedback submitted.");router.back();}}
return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.c}><VasudhaLogo compact/><Text style={s.t}>Rate Your Customer</Text><Text style={s.m}>Your feedback helps VASUDHA CONNECT build a safer, more reliable marketplace.</Text>{fields.map(([k,l])=><View key={k} style={s.b}><Text style={s.l}>{l}</Text><View style={s.row}>{[1,2,3,4,5].map(n=><Pressable key={n} onPress={()=>setScores({...scores,[k]:n})} style={[s.star,scores[k]===n&&s.sel]}><Text style={scores[k]===n?s.w:s.d}>{n}</Text></Pressable>)}</View></View>)}<Text style={s.l}>Would you work with this customer again?</Text><View style={s.row}><Pressable onPress={()=>setAgain(true)} style={[s.choice,again&&s.sel]}><Text style={again?s.w:s.d}>Yes</Text></Pressable><Pressable onPress={()=>setAgain(false)} style={[s.choice,!again&&s.sel]}><Text style={!again?s.w:s.d}>No</Text></Pressable></View><Text style={s.l}>Comment (optional)</Text><TextInput value={comment} onChangeText={setComment} multiline placeholder="Share useful feedback..." style={s.input}/><Pressable onPress={submit} disabled={busy} style={s.p}><Text style={s.w}>{busy?"Submitting...":"Submit Customer Review"}</Text></Pressable></ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1},c:{padding:20,paddingBottom:50},t:{fontSize:28,fontWeight:"800"},m:{opacity:.65,marginTop:6},b:{marginTop:18},l:{fontWeight:"800",marginBottom:8},row:{flexDirection:"row",gap:8},star:{width:40,height:40,borderWidth:1,borderRadius:10,alignItems:"center",justifyContent:"center"},sel:{backgroundColor:"#087D65"},w:{color:"#fff",fontWeight:"800"},d:{color:"#111"},choice:{borderWidth:1,borderRadius:10,paddingHorizontal:22,paddingVertical:10},input:{borderWidth:1,borderRadius:12,padding:12,height:110,textAlignVertical:"top"},p:{marginTop:24,borderRadius:12,padding:15,alignItems:"center",backgroundColor:"#111"}});