import { useState } from "react";
import { Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { useAuth } from "../src/auth/AuthProvider";
import { supabase } from "../src/lib/supabase";
import { VasudhaLogo } from "../src/components/VasudhaLogo";
export default function DeleteAccount(){
 const{session,signOut}=useAuth();const[busy,setBusy]=useState(false);
 async function remove(){if(!session)return;setBusy(true);const{error}=await supabase.functions.invoke("delete-account",{body:{}});if(error){setBusy(false);Alert.alert("Unable to delete account",error.message);return;}await signOut();setBusy(false);router.replace("/auth");}
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.c} keyboardShouldPersistTaps="handled"><VasudhaLogo compact/><Text style={s.t}>Delete your account</Text><Text style={s.m}>This permanently removes your VASUDHA CONNECT account and associated marketplace data.</Text><View style={s.warn}><Text style={s.wt}>This action cannot be undone.</Text><Text style={s.wm}>Your profile, connections, messages, requests, jobs, reviews, complaints, verification documents and other account data will be deleted.</Text></View><Pressable disabled={busy} onPress={()=>Alert.alert("Delete account?","This permanently deletes your account and associated data.",[{text:"Cancel",style:"cancel"},{text:"Delete permanently",style:"destructive",onPress:remove}])} style={s.d}><Text style={s.dt}>{busy?"Deleting...":"Delete account permanently"}</Text></Pressable><Pressable onPress={()=>router.back()} style={s.back}><Text>Cancel</Text></Pressable></ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#fff"},c:{padding:22,paddingBottom:40},t:{fontSize:28,fontWeight:"800",marginTop:10},m:{opacity:.65,marginTop:8,lineHeight:21},warn:{marginTop:22,borderWidth:1,borderColor:"#f0caca",backgroundColor:"#fff7f7",borderRadius:16,padding:16},wt:{fontWeight:"800"},wm:{marginTop:7,lineHeight:20,opacity:.75},d:{marginTop:24,backgroundColor:"#b42318",borderRadius:12,padding:15,alignItems:"center"},dt:{color:"#fff",fontWeight:"800"},back:{padding:16,alignItems:"center"}});