import { useEffect, useState } from "react";
import * as Location from "expo-location";
import { ActivityIndicator, Platform, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";
import { useLocalSearchParams, router } from "expo-router";
import { useAuth } from "../src/auth/AuthProvider";
import { supabase } from "../src/lib/supabase";
import { VasudhaLogo } from "../src/components/VasudhaLogo";
import JobTrackingLocationMap from "../src/components/JobTrackingLocationMap";

const steps=[["worker_accepted","Professional accepted"],["on_the_way","On the Way"],["arrived","Arrived"],["work_started","Work Started"],["work_completed","Work Completed"],["customer_confirmed","Customer Confirmed"]];

export default function JobTracking(){
 const {jobId}=useLocalSearchParams<{jobId:string}>(); const {user,mode}=useAuth(); const [job,setJob]=useState<any>(null); const [privateData,setPrivateData]=useState<any>({}); const [live,setLive]=useState<any>(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{load()},[jobId]);
 useEffect(()=>{if(!jobId||mode!=="professional")return;let watcher:Location.LocationSubscription|undefined;let active=true;(async()=>{const perm=await Location.requestForegroundPermissionsAsync();if(perm.status!=="granted")return;watcher=await Location.watchPositionAsync({accuracy:Location.Accuracy.Balanced,timeInterval:10000,distanceInterval:20},async pos=>{if(!active)return;await supabase.rpc("update_professional_live_location",{p_job_id:jobId,p_latitude:pos.coords.latitude,p_longitude:pos.coords.longitude,p_accuracy_m:pos.coords.accuracy??null});});})();return()=>{active=false;watcher?.remove()}},[jobId,mode]);
 useEffect(()=>{if(!jobId)return; let active=true; const tick=async()=>{const{data}=await supabase.rpc("get_job_live_location",{p_job_id:jobId});if(active)setLive(data?.[0]||null)}; void tick(); const t=setInterval(tick,10000); return()=>{active=false;clearInterval(t)}},[jobId]);
 async function load(){if(!jobId){setLoading(false);return;}const{data}=await supabase.from("jobs").select("*").eq("id",jobId).maybeSingle();setJob(data);if(data){const{data:pd}=await supabase.rpc("get_job_contact_and_location",{p_job_id:jobId});setPrivateData(pd||{});}setLoading(false);}
 const idx=Math.max(0,steps.findIndex(x=>x[0]===job?.status));
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.c}>
   <View style={s.top}><Pressable onPress={()=>router.back()} style={s.back}><Text style={s.backText}>‹</Text></Pressable><VasudhaLogo compact/><View style={{width:24}}/></View>
   <Text style={s.title}>Job Tracking</Text><Text style={s.sub}>{job?.title||"Electrical work at home"}</Text>
   {loading?<View style={s.state}><ActivityIndicator color="#087D65"/><Text style={s.muted}>Loading tracking…</Text></View>:<View style={s.card}>
     <Text style={s.jobId}>JOB · {String(job?.id||jobId||"12345").slice(0,8).toUpperCase()}</Text>
     {steps.map((x,i)=><View key={x[0]} style={s.stepRow}><View style={s.track}>{i<steps.length-1&&<View style={[s.line,i<=idx&&s.doneLine]}/>}<View style={[s.dot,i<=idx?s.active:s.inactive]}>{i<=idx&&<Text style={s.check}>✓</Text>}</View></View><View><Text style={[s.step,i<=idx?s.done:s.future]}>{x[1]}</Text>{i===idx?<Text style={s.current}>Current status</Text>:null}</View></View>)}
   </View>}
   <JobTrackingLocationMap serviceLatitude={privateData?.service_location?.latitude} serviceLongitude={privateData?.service_location?.longitude} serviceLabel={privateData?.service_location?.address} liveLatitude={live?.latitude} liveLongitude={live?.longitude}/><View style={s.info}><Text style={s.infoTitle}>Shared details</Text><Text style={s.infoLine}>📍 Service location</Text><Text style={s.muted}>{privateData?.service_location?.address||"Location is available after job acceptance."}</Text>{privateData?.customer?.phone?<Text style={s.infoLine}>Customer: {privateData.customer.phone}</Text>:null}{privateData?.professional?.phone?<Text style={s.infoLine}>Professional: {privateData.professional.phone}</Text>:null}{live?<Text style={s.live}>● Professional live location updated {new Date(live.updated_at).toLocaleTimeString()}</Text>:job?.status&&["worker_accepted","on_the_way","arrived","work_started"].includes(job.status)?<Text style={s.muted}>Waiting for the professional to share live location…</Text>:null}</View>
   <Pressable style={s.secondary} onPress={()=>router.back()}><Text style={s.secondaryText}>Back to My Jobs</Text></Pressable>
 </ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#fff"},c:{padding:20,paddingBottom:40},top:{height:46,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},back:{width:40,height:40,borderRadius:20,backgroundColor:"#f2f7f5",alignItems:"center",justifyContent:"center"},backText:{fontSize:30,color:"#13201c"},more:{fontSize:24,color:"#087D65"},title:{fontSize:28,fontWeight:"900",color:"#13201c",marginTop:18},sub:{color:"#66736e",marginTop:5},card:{borderWidth:1,borderColor:"#e0e8e5",borderRadius:18,padding:18,marginTop:18},jobId:{fontSize:11,color:"#87928e",marginBottom:14},stepRow:{flexDirection:"row",minHeight:52},track:{width:24,alignItems:"center",position:"relative"},line:{position:"absolute",top:16,bottom:0,width:2,backgroundColor:"#dfe7e4"},doneLine:{backgroundColor:"#087D65"},dot:{width:16,height:16,borderRadius:8,borderWidth:1,alignItems:"center",justifyContent:"center",zIndex:2},active:{backgroundColor:"#087D65",borderColor:"#087D65"},inactive:{backgroundColor:"#fff",borderColor:"#cfdad6"},check:{fontSize:9,color:"#fff",fontWeight:"900"},step:{marginLeft:10,fontSize:14},done:{fontWeight:"800",color:"#13201c"},future:{color:"#9aa6a2"},current:{fontSize:11,color:"#087D65",fontWeight:"800",marginLeft:10,marginTop:2},state:{alignItems:"center",paddingVertical:50},muted:{color:"#66736e",marginTop:5},info:{borderWidth:1,borderColor:"#e0e8e5",borderRadius:16,padding:16,marginTop:14},infoTitle:{fontSize:17,fontWeight:"900",color:"#13201c",marginBottom:12},infoLine:{fontWeight:"800",marginTop:8},secondary:{marginTop:14,borderWidth:1,borderColor:"#087D65",borderRadius:12,minHeight:48,alignItems:"center",justifyContent:"center"},secondaryText:{color:"#087D65",fontWeight:"900"},map:{height:200,borderRadius:18,marginTop:14,overflow:"hidden",backgroundColor:"#e9f3ef",alignItems:"center",justifyContent:"center"},mapText:{backgroundColor:"#fff",paddingHorizontal:12,paddingVertical:7,borderRadius:10,fontWeight:"800"},live:{color:"#087D65",fontWeight:"800",marginTop:10}});

