import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";
import { useLocalSearchParams, router } from "expo-router";
import { supabase } from "../src/lib/supabase";
import { VasudhaLogo } from "../src/components/VasudhaLogo";

export default function JobDetails(){
 const {jobId}=useLocalSearchParams<{jobId:string}>(); const [job,setJob]=useState<any>(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{if(jobId)supabase.from("jobs").select("*").eq("id",jobId).maybeSingle().then(({data})=>{setJob(data);setLoading(false)})},[jobId]);
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.c}>
   <View style={s.top}><Pressable onPress={()=>router.back()} style={s.back}><Text style={s.backText}>‹</Text></Pressable><VasudhaLogo compact/><Text style={s.more}>⋯</Text></View>
   <Text style={s.title}>Job Details</Text>
   {loading?<View style={s.state}><ActivityIndicator color="#087D65"/><Text style={s.muted}>Loading job…</Text></View>:<><View style={s.card}><Text style={s.name}>{job?.title||"Electrical work at home"}</Text><Text style={s.badge}>{job?.status||"In Progress"}</Text><Text style={s.label}>Customer</Text><Text style={s.value}>Customer</Text><Text style={s.label}>Job location</Text><Text style={s.value}>Saved service location</Text><Text style={s.label}>Agreed amount</Text><Text style={s.amount}>₹{Number(job?.agreed_amount_inr||0).toLocaleString("en-IN")}</Text></View><View style={s.map}><View style={s.route}/><Text style={s.mapText}>Service location</Text></View><View style={s.worker}><View style={s.avatar}><Text>RK</Text></View><View style={{flex:1}}><Text style={s.workerName}>Professional</Text><Text style={s.muted}>Verified • Available</Text></View></View><View style={s.actions}><Pressable style={s.secondary}><Text style={s.secondaryText}>Call</Text></Pressable><Pressable style={s.primary}><Text style={s.primaryText}>Message</Text></Pressable></View><Pressable style={s.track} onPress={()=>router.push({pathname:"/job-tracking",params:{jobId}})}><Text style={s.trackText}>Track Job →</Text></Pressable></>}
 </ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#fff"},c:{padding:20,paddingBottom:40},top:{height:46,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},back:{width:40,height:40,borderRadius:20,backgroundColor:"#f2f7f5",alignItems:"center",justifyContent:"center"},backText:{fontSize:30},more:{fontSize:24,color:"#087D65"},title:{fontSize:28,fontWeight:"900",color:"#13201c",marginTop:18},card:{borderWidth:1,borderColor:"#e0e8e5",borderRadius:18,padding:16,marginTop:18},name:{fontSize:18,fontWeight:"900",color:"#13201c"},badge:{alignSelf:"flex-start",backgroundColor:"#e7f7f2",color:"#087D65",paddingHorizontal:10,paddingVertical:5,borderRadius:12,fontWeight:"800",marginTop:8},label:{fontSize:11,color:"#66736e",marginTop:16},value:{fontWeight:"800",marginTop:3},amount:{fontSize:22,fontWeight:"900",color:"#087D65",marginTop:3},map:{height:180,borderRadius:18,marginTop:14,backgroundColor:"#e9f3ef",overflow:"hidden",alignItems:"center",justifyContent:"center"},route:{width:"70%",height:3,backgroundColor:"#087D65",transform:[{rotate:"-18deg"}]},mapText:{position:"absolute",bottom:12,backgroundColor:"#fff",paddingHorizontal:10,paddingVertical:6,borderRadius:10,fontWeight:"800"},worker:{flexDirection:"row",alignItems:"center",gap:12,borderWidth:1,borderColor:"#e0e8e5",borderRadius:16,padding:14,marginTop:14},avatar:{width:48,height:48,borderRadius:24,backgroundColor:"#e7f7f2",alignItems:"center",justifyContent:"center"},workerName:{fontWeight:"900"},muted:{color:"#66736e",marginTop:4},actions:{flexDirection:"row",gap:10,marginTop:12},secondary:{flex:1,borderWidth:1,borderColor:"#087D65",borderRadius:12,minHeight:48,alignItems:"center",justifyContent:"center"},secondaryText:{color:"#087D65",fontWeight:"900"},primary:{flex:1,backgroundColor:"#087D65",borderRadius:12,minHeight:48,alignItems:"center",justifyContent:"center"},primaryText:{color:"#fff",fontWeight:"900"},track:{marginTop:12,borderRadius:12,minHeight:48,alignItems:"center",justifyContent:"center",backgroundColor:"#e7f7f2"},trackText:{color:"#087D65",fontWeight:"900"},state:{alignItems:"center",paddingVertical:50}});
