import { useEffect, useState } from "react";
import { Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { supabase } from "../src/lib/supabase";
import { useAuth } from "../src/auth/AuthProvider";

export default function ProfessionalDashboard(){
 const {user}=useAuth(); const [requests,setRequests]=useState<any[]>([]); const [jobs,setJobs]=useState<any[]>([]); const [profile,setProfile]=useState<any>(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{load();},[user?.id]);
 async function load(){if(!user)return;setLoading(true);const [{data:p},{data:r},{data:j}]=await Promise.all([
  supabase.from("professional_profiles").select("headline,verification_status,is_available,trust_score,response_rate,completion_rate,cancellation_rate").eq("user_id",user.id).maybeSingle(),
  supabase.from("service_requests").select("id,title,description,budget_min_inr,budget_max_inr,status,created_at,customer_id").eq("professional_id",user.id).order("created_at",{ascending:false}).limit(20),
  supabase.from("jobs").select("id,title,agreed_amount_inr,status,created_at,customer_id").eq("professional_id",user.id).order("created_at",{ascending:false}).limit(20)
 ]);setProfile(p);setRequests(r||[]);setJobs(j||[]);setLoading(false);}
 async function accept(job:any){const {error}=await supabase.rpc("update_job_status",{p_job_id:job.id,p_status:"worker_accepted"});if(error)Alert.alert("Unable to accept",error.message);else load();}
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container}><Text style={s.title}>Professional Dashboard</Text><Text style={s.subtitle}>Manage your VASUDHA CONNECT work</Text>{loading?<Text style={s.muted}>Loading...</Text>:<><View style={s.stats}><View style={s.stat}><Text style={s.num}>{Math.round(profile?.trust_score||0)}</Text><Text>Trust</Text></View><View style={s.stat}><Text style={s.num}>{profile?.completion_rate||0}%</Text><Text>Completion</Text></View><View style={s.stat}><Text style={s.num}>{profile?.response_rate||0}%</Text><Text>Response</Text></View></View><View style={s.card}><Text style={s.cardTitle}>Profile</Text><Text>{profile?.verification_status==="verified"?"✓ Verified":"Verification: "+(profile?.verification_status||"unverified")}</Text><Text>{profile?.is_available?"Available for work":"Currently unavailable"}</Text><Pressable onPress={()=>router.push("/professional-profile")} style={s.secondary}><Text>Edit Professional Profile</Text></Pressable></View><Text style={s.section}>Incoming Requests</Text>{requests.length===0?<Text style={s.muted}>No service requests yet.</Text>:requests.map(x=><View key={x.id} style={s.card}><Text style={s.name}>{x.title}</Text><Text style={s.desc}>{x.description}</Text>{x.budget_min_inr!=null?<Text>Budget: ₹{Number(x.budget_min_inr).toLocaleString("en-IN")} - ₹{Number(x.budget_max_inr||x.budget_min_inr).toLocaleString("en-IN")}</Text>:null}<Text style={s.status}>{x.status}</Text>{x.status==="requested"?<Pressable onPress={()=>router.push({pathname:"/quote",params:{requestId:x.id}})} style={s.primary}><Text style={s.primaryText}>Submit Quotation</Text></Pressable>:null}</View>)}<Text style={s.section}>My Jobs</Text>{jobs.length===0?<Text style={s.muted}>No jobs yet.</Text>:jobs.map(x=><View key={x.id} style={s.card}><Text style={s.name}>{x.title}</Text><Text>₹{Number(x.agreed_amount_inr).toLocaleString("en-IN")}</Text><Text style={s.status}>{x.status}</Text>{x.status==="quote_accepted"?<Pressable onPress={()=>accept(x)} style={s.primary}><Text style={s.primaryText}>Accept Job</Text></Pressable>:null}</View>)}</>}</ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1},container:{padding:20,paddingBottom:50},title:{fontSize:28,fontWeight:"800"},subtitle:{opacity:.6,marginTop:5},stats:{flexDirection:"row",gap:10,marginTop:20},stat:{flex:1,borderWidth:1,borderRadius:14,padding:14,alignItems:"center"},num:{fontSize:22,fontWeight:"800"},card:{borderWidth:1,borderRadius:16,padding:16,marginTop:12},cardTitle:{fontSize:18,fontWeight:"800"},name:{fontSize:17,fontWeight:"800"},desc:{marginVertical:8,opacity:.75},status:{fontWeight:"800",marginTop:8},section:{fontSize:21,fontWeight:"800",marginTop:25},muted:{opacity:.6,marginTop:8},primary:{marginTop:12,borderRadius:12,padding:13,alignItems:"center",backgroundColor:"#111"},primaryText:{color:"#fff",fontWeight:"800"},secondary:{marginTop:12,borderWidth:1,borderRadius:12,padding:12,alignItems:"center"}});
