import {useEffect,useMemo,useState} from "react";
import {Alert,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View} from "react-native";
import * as Location from "expo-location";
import {router} from "expo-router";
import {useAuth} from "../src/auth/AuthProvider";
import {supabase} from "../src/lib/supabase";
import {VasudhaLogo} from "../src/components/VasudhaLogo";
import {ServicePicker,ServiceSelection} from "../src/components/ServicePicker";

const steps=["Profile","Services","Service Area","Verification"];
export default function ProfessionalOnboarding(){
 const{session}=useAuth(),uid=session?.user.id;
 const[step,setStep]=useState(0),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 const[fullName,setFullName]=useState(""),[headline,setHeadline]=useState(""),[about,setAbout]=useState(""),[years,setYears]=useState("0"),[status,setStatus]=useState("unverified");
 const[selection,setSelection]=useState<ServiceSelection>({categoryId:null,categoryName:null,serviceId:null,serviceName:null,legacySkillId:null,subServiceId:null,subServiceName:null});
 const[services,setServices]=useState<any[]>([]),[area,setArea]=useState({label:"",city:"",state:"",radius_km:"10"}),[baseLocation,setBaseLocation]=useState<{latitude:number;longitude:number}|null>(null);
 useEffect(()=>{if(uid)load();else setLoading(false)},[uid]);
 async function load(){
  setLoading(true);
  const[p,ps,a,profile]=await Promise.all([
   supabase.from("professional_profiles").select("headline,about,years_experience,verification_status").eq("user_id",uid).maybeSingle(),
   supabase.from("professional_sub_services").select("sub_service_id").eq("professional_id",uid),
   supabase.from("service_areas").select("id,label,city,state,radius_km").eq("professional_id",uid).order("created_at").limit(1),
   supabase.from("profiles").select("full_name,display_name").eq("id",uid).maybeSingle()
  ]);
  if(profile.data)setFullName(profile.data.full_name||profile.data.display_name||"");
  if(p.data){setHeadline(p.data.headline||"");setAbout(p.data.about||"");setYears(String(p.data.years_experience||0));setStatus(p.data.verification_status||"unverified")}
  if(a.data?.[0])setArea({label:a.data[0].label||"",city:a.data[0].city||"",state:a.data[0].state||"",radius_km:String(a.data[0].radius_km||10)});
  if(ps.data?.length){const{data}=await supabase.from("service_catalogue_sub_services").select("id,name,service_id,service_catalogue_services(name)").in("id",ps.data.map((x:any)=>x.sub_service_id));setServices((data||[]).map((x:any)=>({id:x.id,name:x.name,serviceName:x.service_catalogue_services?.name||"Service"})))}
  setLoading(false);
 }
 const profileOk=useMemo(()=>fullName.trim().length>=2&&headline.trim().length>=3&&about.trim().length>=10,[fullName,headline,about]);
 async function saveProfile(){if(!uid||!profileOk){Alert.alert("Complete profile","Add your name, a headline and at least a short description.");return false}const{error:profileError}=await supabase.from("profiles").update({full_name:fullName.trim(),display_name:fullName.trim()}).eq("id",uid);if(profileError){Alert.alert("Profile save failed",profileError.message);return false}const{error}=await supabase.from("professional_profiles").update({headline:headline.trim(),about:about.trim(),years_experience:Number(years)||0}).eq("user_id",uid);if(error){Alert.alert("Save failed",error.message);return false}return true}
 async function addService(v:ServiceSelection){if(!uid||!v.subServiceId)return false;if(services.some(x=>x.id===v.subServiceId))return true;const{error}=await supabase.from("professional_sub_services").insert({professional_id:uid,sub_service_id:v.subServiceId,is_primary:services.length===0,years_experience:Number(years)||0});if(error&&error.code!=="23505"){Alert.alert("Service save failed",error.message);return false}setServices(z=>[...z,{id:v.subServiceId,name:v.subServiceName||"Sub-service",serviceName:v.serviceName||"Service"}]);return true}
 async function saveArea(){if(!uid||area.label.trim().length<2){Alert.alert("Service area","Enter your main area/locality.");return false}let coords=baseLocation;try{if(!coords){const perm=await Location.requestForegroundPermissionsAsync();if(perm.status==="granted"){const pos=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Balanced});coords={latitude:pos.coords.latitude,longitude:pos.coords.longitude};setBaseLocation(coords);}}}catch{}if(!coords){Alert.alert("Location required","VASUDHA uses your service-area coordinates to show you to nearby customers. Allow location access or try again from a device with location enabled.");return false}const{data}=await supabase.from("service_areas").select("id").eq("professional_id",uid).limit(1);const payload={label:area.label.trim(),city:area.city.trim()||null,state:area.state.trim()||null,radius_km:Number(area.radius_km)||10};const r=data?.[0]?await supabase.from("service_areas").update(payload).eq("id",data[0].id):await supabase.from("service_areas").insert({...payload,professional_id:uid,is_primary:true});if(r.error){Alert.alert("Area save failed",r.error.message);return false}const{error:profileError}=await supabase.from("professional_profiles").update({base_latitude:coords.latitude,base_longitude:coords.longitude,service_radius_km:Number(area.radius_km)||10}).eq("user_id",uid);if(profileError){Alert.alert("Location save failed",profileError.message);return false}return true}
 async function next(){if(busy)return;setBusy(true);try{if(step===0){if(await saveProfile())setStep(1)}else if(step===1){if(!services.length){Alert.alert("Add services","Select General / Any or a specific sub-service.");return}setStep(2)}else if(step===2){if(await saveArea())setStep(3)}else router.replace("/professional-verification")}finally{setBusy(false)}}
 async function useLocation(){try{const p=await Location.requestForegroundPermissionsAsync();if(p.status!=="granted"){Alert.alert("Location permission","Enter your area manually.");return}const pos=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Balanced});setBaseLocation({latitude:pos.coords.latitude,longitude:pos.coords.longitude});const g=(await Location.reverseGeocodeAsync(pos.coords))[0];setArea(x=>({...x,label:g?.district||g?.subregion||g?.city||"",city:g?.city||"",state:g?.region||""}))}catch{Alert.alert("Location unavailable","Please enter your area manually.")}}
 if(loading)return <SafeAreaView style={s.safe}><View style={s.loading}><Text>Preparing registration…</Text></View></SafeAreaView>;
 if(!uid)return <SafeAreaView style={s.safe}><View style={s.loading}><Text>Please sign in to continue.</Text></View></SafeAreaView>;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.c} keyboardShouldPersistTaps="handled"><View style={s.top}><Pressable accessibilityRole="button" accessibilityLabel="Back to profile" onPress={()=>{if(router.canGoBack())router.back();else router.replace("/home")}}><Text style={s.back}>‹</Text></Pressable><VasudhaLogo compact/><View style={{width:30}}/></View><Text style={s.title}>Professional Registration</Text><Text style={s.sub}>Complete these steps to become visible to customers.</Text>
  <View style={s.progress}>{steps.map((x,i)=><View key={x} style={s.pi}><View style={[s.circle,i<=step&&s.on]}><Text style={i<=step?s.ct:s.co}>{i<step?"✓":i+1}</Text></View><Text style={[s.pt,i===step&&s.pon]}>{x}</Text></View>)}</View>
  {step===0&&<View style={s.card}><Text style={s.sec}>1. Professional profile</Text><Text style={s.lab}>Your name *</Text><TextInput style={s.input} value={fullName} onChangeText={setFullName} placeholder="Full name" autoCapitalize="words"/><Text style={s.lab}>Professional headline *</Text><TextInput style={s.input} value={headline} onChangeText={setHeadline} placeholder="e.g. Experienced Electrician"/><Text style={s.lab}>About your work *</Text><TextInput style={[s.input,s.multi]} value={about} onChangeText={setAbout} multiline placeholder="Experience, strengths and the work you do"/><Text style={s.lab}>Years of experience</Text><TextInput style={s.input} value={years} onChangeText={setYears} keyboardType="number-pad"/></View>}
  {step===1&&<View style={s.card}><Text style={s.sec}>2. Services you provide</Text><Text style={s.help}>Choose a main service, then select <Text style={s.bold}>General / Any</Text> for the whole service or a specific sub-service. Add multiple services.</Text><ServicePicker value={selection} onChange={async v=>{setSelection(v);if(v.subServiceId)await addService(v)}}/><View style={s.list}>{services.map((x,i)=><View key={x.id} style={s.item}><View style={{flex:1}}><Text style={s.bold}>{x.serviceName}</Text><Text style={s.muted}>{x.name}{i===0?" · Primary":""}</Text></View><Pressable onPress={async()=>{await supabase.from("professional_sub_services").delete().eq("professional_id",uid).eq("sub_service_id",x.id);setServices(z=>z.filter(y=>y.id!==x.id))}}><Text style={s.remove}>Remove</Text></Pressable></View>)}</View></View>}
  {step===2&&<View style={s.card}><Text style={s.sec}>3. Service area</Text><Text style={s.help}>Customers see your service coverage, not your private home address.</Text><Text style={s.lab}>Area / locality *</Text><TextInput style={s.input} value={area.label} onChangeText={v=>setArea({...area,label:v})} placeholder="e.g. Lanka, Varanasi"/><Pressable style={s.secondary} onPress={useLocation}><Text style={s.secondaryText}>Use my current area</Text></Pressable><View style={s.row}><TextInput style={[s.input,s.half]} value={area.city} onChangeText={v=>setArea({...area,city:v})} placeholder="City"/><TextInput style={[s.input,s.half]} value={area.state} onChangeText={v=>setArea({...area,state:v})} placeholder="State"/></View><Text style={s.lab}>Service radius (km)</Text><TextInput style={s.input} value={area.radius_km} onChangeText={v=>setArea({...area,radius_km:v})} keyboardType="number-pad"/></View>}
  {step===3&&<View style={s.card}><Text style={s.sec}>4. Identity & verification</Text><Text style={s.help}>Your profile is reviewed before it appears in customer search.</Text><View style={s.status}><Text>Current status</Text><Text style={s.badge}>{status.toUpperCase()}</Text></View><Pressable style={s.primary} onPress={()=>router.push("/professional-verification")}><Text style={s.primaryText}>{status==="verified"?"View verification":"Submit verification documents"}</Text></Pressable></View>}
  <View style={s.nav}>{step>0?<Pressable style={s.secondaryBtn} onPress={()=>setStep(step-1)}><Text>Back</Text></Pressable>:<View/>}<Pressable disabled={busy} style={s.primaryBtn} onPress={next}><Text style={s.primaryText}>{busy?"Saving…":step===3?"Open verification":"Continue"}</Text></Pressable></View><Text style={s.footer}>You can update your profile, services and availability later.</Text>
 </ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#fff"},c:{padding:20,paddingBottom:40},top:{height:42,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},back:{fontSize:30},title:{fontSize:28,fontWeight:"900",color:"#13201c",marginTop:18},sub:{color:"#66736e",marginTop:5},progress:{flexDirection:"row",justifyContent:"space-between",marginTop:22},pi:{alignItems:"center",flex:1},circle:{width:30,height:30,borderRadius:15,borderWidth:1,borderColor:"#cfdad6",alignItems:"center",justifyContent:"center"},on:{backgroundColor:"#087D65",borderColor:"#087D65"},ct:{color:"#fff",fontWeight:"900"},co:{color:"#66736e",fontWeight:"800"},pt:{fontSize:10,color:"#66736e",marginTop:5},pon:{color:"#087D65",fontWeight:"900"},card:{marginTop:18,borderWidth:1,borderColor:"#e0e8e5",borderRadius:16,padding:16},sec:{fontSize:19,fontWeight:"900"},lab:{fontWeight:"800",marginTop:17,marginBottom:7},input:{borderWidth:1,borderColor:"#cfdad6",borderRadius:12,padding:12,minHeight:48,color:"#13201c"},multi:{minHeight:110,textAlignVertical:"top"},help:{fontSize:12,color:"#66736e",lineHeight:18,marginTop:7},bold:{fontWeight:"800",color:"#13201c"},list:{marginTop:12},item:{flexDirection:"row",alignItems:"center",gap:10,borderTopWidth:1,borderTopColor:"#edf1ef",paddingVertical:11},muted:{fontSize:12,color:"#66736e"},remove:{color:"#b42318",fontWeight:"800"},secondary:{marginTop:12,borderWidth:1,borderColor:"#087D65",borderRadius:12,padding:12,alignItems:"center"},secondaryText:{color:"#087D65",fontWeight:"900"},row:{flexDirection:"row",gap:9},half:{flex:1},status:{marginTop:16,padding:13,borderRadius:12,backgroundColor:"#f2f8f6",flexDirection:"row",justifyContent:"space-between"},badge:{fontWeight:"900",color:"#087D65"},primary:{marginTop:14,borderRadius:12,padding:14,backgroundColor:"#087D65",alignItems:"center"},primaryText:{color:"#fff",fontWeight:"900"},nav:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginTop:18,gap:10},secondaryBtn:{minWidth:90,borderWidth:1,borderColor:"#cfdad6",borderRadius:12,padding:14,alignItems:"center"},primaryBtn:{flex:1,minHeight:50,borderRadius:12,backgroundColor:"#087D65",alignItems:"center",justifyContent:"center"},footer:{textAlign:"center",fontSize:12,color:"#66736e",marginTop:16},loading:{flex:1,alignItems:"center",justifyContent:"center"}});
