import{useEffect,useState}from"react";import{ActivityIndicator,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View}from"react-native";import{router}from"expo-router";import{useAuth}from"../src/auth/AuthProvider";import{VasudhaLogo}from"../src/components/VasudhaLogo";import{KamproPage,KamproHeader,KamproCard,KamproPrimary,KamproSection}from"../src/components/KamproUI";import{AppBottomNav}from"../src/components/AppBottomNav";import{supabase}from"../src/lib/supabase";

export default function Profile(){
 const{user,mode}=useAuth();const[loading,setLoading]=useState(true);const[data,setData]=useState<any>(null);
 useEffect(()=>{load()},[user?.id,mode]);
 async function load(){if(!user){setLoading(false);return;}setLoading(true);if(mode==="professional"){const[p,j,r]=await Promise.all([supabase.from("professional_profiles").select("verification_status,is_available,trust_score,response_rate,completion_rate").eq("user_id",user.id).maybeSingle(),supabase.from("jobs").select("id,status").eq("professional_id",user.id),supabase.from("customer_job_reviews").select("punctuality,work_quality,professional_behaviour,communication,value_for_money,reliability,safety_care").eq("professional_id",user.id)]);const jobs=j.data||[];const reviews=r.data||[];const rating=reviews.length?reviews.reduce((sum:number,x:any)=>sum+(Number(x.punctuality)+Number(x.work_quality)+Number(x.professional_behaviour)+Number(x.communication)+Number(x.value_for_money)+Number(x.reliability)+Number(x.safety_care))/7,0)/reviews.length:null;setData({...p.data,rating,completedJobs:jobs.filter((x:any)=>x.status==="customer_confirmed").length,totalJobs:jobs.length});}else{const{data}=await supabase.rpc("get_customer_reputation",{p_customer_id:user.id});setData(data||{});}setLoading(false);}
 return <><KamproPage><View style={s.top}><VasudhaLogo/><Pressable onPress={load} style={s.refresh}><Text>↻</Text></Pressable></View>
 <KamproHeader title={mode==="professional"?"My Professional Profile":"My Customer Profile"} subtitle={mode==="professional"?"Your reputation and professional performance on KAMPRO.":"Your profile helps professionals understand who they are working with."}/>
 {loading?<View style={s.state}><ActivityIndicator color="#FF4B1F"/><Text style={s.muted}>Loading profile…</Text></View>:mode==="professional"?<><View style={s.trust}><View style={{flex:1}}><Text style={s.trustTitle}>Professional Trust</Text><Text style={s.muted}>Your reputation on KAMPRO</Text></View><Text style={s.score}>{Math.round(data?.trust_score||0)}</Text><View style={s.bar}><View style={[s.fill,{width:(Math.max(0,Math.min(100,Number(data?.trust_score||0))))+"%"}]}/></View><Text style={s.muted}>{data?.verification_status==="verified"?"✓ Verified":"Verification: "+(data?.verification_status||"pending")} • {data?.is_available?"Available now":"Unavailable"}</Text></View>
 <View style={s.stats}><Stat n={Math.round(data?.trust_score||0)} l="Trust"/><Stat n={data?.rating==null?"—":Number(data.rating).toFixed(1)+"★"} l="Rating"/><Stat n={data?.totalJobs?Math.round(data.completedJobs/data.totalJobs*100):0} l="Completion %"/></View>
 <Pressable style={s.primary} onPress={()=>router.push("/professional-profile")}><Text style={s.primaryText}>Edit Professional Profile</Text></Pressable>
 <View style={s.menu}><Item title="My Jobs" sub="Manage assigned work" onPress={()=>router.push("/jobs")}/><Item title="Availability & Skills" sub="Update services and service areas" onPress={()=>router.push("/professional-profile")}/><Item title="My Performance" sub="Trust, completion and response" onPress={()=>router.push("/professional-dashboard")}/><Item title="Complaints & Reports" sub="Track complaint status and updates" onPress={()=>router.push("/complaints")}/></View></>:<><View style={s.trust}><View style={{flex:1}}><Text style={s.trustTitle}>Customer Trust</Text><Text style={s.muted}>Your reputation on KAMPRO</Text></View><Text style={s.score}>{Math.round(data?.trust_score||0)}</Text><View style={s.bar}><View style={[s.fill,{width:(Math.max(0,Math.min(100,Number(data?.trust_score||0))))+"%"}]}/></View><Text style={s.muted}>{data?.jobs_completed||0} completed jobs • {data?.reviews_received||0} reviews • {data?.would_work_again_pct||0}% would work again</Text></View>
 <Pressable style={s.primary} onPress={()=>router.push("/customer-profile")}><Text style={s.primaryText}>Edit Customer Profile</Text></Pressable>
 <View style={s.menu}><Item title="My Connections" sub="Your unlocked professionals" onPress={()=>router.push("/connections")}/><Item title="My Jobs" sub="Track work and confirm completion" onPress={()=>router.push("/jobs")}/><Item title="Find Professionals" sub="Search trusted professionals nearby" onPress={()=>router.push("/marketplace")}/><Item title="Complaints & Reports" sub="Track complaint status and updates" onPress={()=>router.push("/complaints")}/></View></>}
 <Text style={s.section}>Account</Text><View style={s.menu}><Item title="Notifications" sub="Updates, messages and jobs" onPress={()=>router.push("/notifications")}/><Item title="Privacy Policy" sub="How your information is handled" onPress={()=>router.push("/privacy-policy")}/><Item title="Terms of Service" sub="Marketplace terms and responsibilities" onPress={()=>router.push("/terms")}/><Item title="Delete account" sub="Permanently remove your account" danger onPress={()=>router.push("/delete-account")}/></View>
 </KamproPage><AppBottomNav active="profile"/></>
}
function Stat({n,l}:{n:any;l:string}){return <View style={s.stat}><Text style={s.statN}>{n}</Text><Text style={s.statL}>{l}</Text></View>}
function Item({title,sub,onPress,danger}:{title:string;sub:string;onPress:()=>void;danger?:boolean}){return <Pressable onPress={onPress} style={s.item}><View style={{flex:1}}><Text style={[s.itemTitle,danger&&s.danger]}>{title}</Text><Text style={s.muted}>{sub}</Text></View><Text style={s.arrow}>›</Text></Pressable>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#fff"},c:{padding:20,paddingBottom:104},top:{height:48,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},refresh:{width:40,height:40,borderRadius:20,backgroundColor:"#F7F8FA",alignItems:"center",justifyContent:"center"},t:{fontSize:28,fontWeight:"900",color:"#10233F",marginTop:10},sub:{color:"#6B7280",marginTop:6,lineHeight:19},trust:{marginTop:18,borderWidth:1,borderColor:"#b9ddd4",borderRadius:16,padding:16,backgroundColor:"#f4fbf8",flexDirection:"row",flexWrap:"wrap",alignItems:"center"},trustTitle:{fontSize:17,fontWeight:"900",color:"#10233F"},score:{fontSize:28,fontWeight:"900",color:"#FF4B1F"},bar:{height:7,backgroundColor:"#dceae5",borderRadius:5,width:"100%",marginTop:12,overflow:"hidden"},fill:{height:"100%",backgroundColor:"#FF4B1F"},stats:{flexDirection:"row",gap:10,marginTop:12},stat:{flex:1,borderWidth:1,borderColor:"#E7EAF0",borderRadius:14,padding:13,alignItems:"center"},statN:{fontSize:21,fontWeight:"900",color:"#FF4B1F"},statL:{fontSize:11,color:"#6B7280",marginTop:3},primary:{marginTop:14,minHeight:48,borderRadius:12,backgroundColor:"#FF4B1F",alignItems:"center",justifyContent:"center"},primaryText:{color:"#fff",fontWeight:"900"},menu:{marginTop:10,borderWidth:1,borderColor:"#E7EAF0",borderRadius:16,overflow:"hidden"},item:{padding:15,borderBottomWidth:1,borderBottomColor:"#EEF0F4",flexDirection:"row",alignItems:"center",minWidth:0},itemTitle:{fontSize:16,fontWeight:"800",color:"#10233F"},arrow:{fontSize:28,color:"#FF4B1F"},section:{fontSize:20,fontWeight:"900",marginTop:24,color:"#10233F"},muted:{color:"#6B7280",marginTop:4,lineHeight:18},state:{alignItems:"center",paddingVertical:35},danger:{color:"#b42318"}});
