import * as Location from "expo-location";
import { useEffect, useState } from "react";
import { Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Switch, Text, TextInput, View } from "react-native";
import { supabase } from "../src/lib/supabase";
import { useAuth } from "../src/auth/AuthProvider";
type Skill={id:string;name:string;category:string};
export default function ProfessionalProfile(){
 const{session}=useAuth();const[headline,setHeadline]=useState(""),[about,setAbout]=useState(""),[years,setYears]=useState(""),[radius,setRadius]=useState("10"),[available,setAvailable]=useState(false),[skills,setSkills]=useState<Skill[]>([]),[selected,setSelected]=useState<string[]>([]),[city,setCity]=useState(""),[state,setState]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{load();},[]);
 async function load(){if(!session)return;const[{data:p},{data:sk},{data:ps}]=await Promise.all([supabase.from("professional_profiles").select("*").eq("user_id",session.user.id).maybeSingle(),supabase.from("skills").select("id,name,category").eq("is_active",true).order("category").order("name"),supabase.from("professional_skills").select("skill_id").eq("professional_id",session.user.id)]);if(p){setHeadline(p.headline||"");setAbout(p.about||"");setYears(String(p.years_experience||""));setRadius(String(p.service_radius_km||10));setAvailable(!!p.is_available);}setSkills(sk||[]);setSelected((ps||[]).map(x=>x.skill_id));}
 function toggleSkill(id:string){setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);}
 async function locate(){const perm=await Location.requestForegroundPermissionsAsync();if(perm.status!=="granted")return Alert.alert("Location needed","Allow location access to set your service location.");const pos=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Balanced});await saveLocation(pos.coords.latitude,pos.coords.longitude);}
 async function saveLocation(lat:number,lon:number){if(!session)return;const{error}=await supabase.from("professional_profiles").update({base_latitude:lat,base_longitude:lon}).eq("user_id",session.user.id);if(error)Alert.alert("Location","Could not save location.");else Alert.alert("Location","Service location updated.");}
 async function save(){if(!session)return;setBusy(true);try{const{error}=await supabase.from("professional_profiles").update({headline:headline.trim()||null,about:about.trim()||null,years_experience:Number(years)||0,service_radius_km:Number(radius)||10,is_available:available}).eq("user_id",session.user.id);if(error)throw error;await supabase.from("professional_skills").delete().eq("professional_id",session.user.id);if(selected.length) {const{error:e}=await supabase.from("professional_skills").insert(selected.map(skill_id=>({professional_id:session.user.id,skill_id})));if(e)throw e;}Alert.alert("Saved","Your professional profile has been updated.");}catch(e){Alert.alert("Save failed",e instanceof Error?e.message:"Please try again.");}finally{setBusy(false);}}
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container}><Text style={s.title}>Professional Profile</Text><Text style={s.sub}>Complete your profile so customers can find you.</Text>
 <Text style={s.label}>Professional headline</Text><TextInput style={s.input} placeholder="e.g. Experienced electrician" value={headline} onChangeText={setHeadline}/>
 <Text style={s.label}>About you</Text><TextInput style={[s.input,s.multi]} placeholder="Describe your experience and services" value={about} onChangeText={setAbout} multiline/>
 <Text style={s.label}>Years of experience</Text><TextInput style={s.input} keyboardType="number-pad" value={years} onChangeText={setYears}/>
 <Text style={s.label}>Skills</Text><View style={s.wrap}>{skills.map(x=><Pressable key={x.id} onPress={()=>toggleSkill(x.id)} style={[s.chip,selected.includes(x.id)&&s.chipSelected]}><Text>{x.name}</Text></Pressable>)}</View>
 <Text style={s.label}>Service radius: {radius} km</Text><View style={s.row}>{[5,10,25,50].map(x=><Pressable key={x} onPress={()=>setRadius(String(x))} style={[s.radius,radius===String(x)&&s.selected]}><Text>{x} km</Text></Pressable>)}</View>
 <View style={s.avail}><View><Text style={s.label}>Available for jobs</Text><Text style={s.muted}>Customers can see you as available.</Text></View><Switch value={available} onValueChange={setAvailable}/></View>
 <Pressable onPress={locate} style={s.secondary}><Text style={s.buttonText}>Set my service location</Text></Pressable>
 <Pressable disabled={busy} onPress={save} style={s.primary}><Text style={s.buttonText}>{busy?"Saving...":"Save professional profile"}</Text></Pressable>
 <Text style={s.note}>Verification status is controlled by VASUDHA CONNECT administration. Only verified professionals appear in nearby search.</Text>
 </ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1},container:{padding:20,paddingBottom:50},title:{fontSize:27,fontWeight:"800"},sub:{marginTop:5,opacity:.65,marginBottom:22},label:{fontWeight:"700",marginTop:14,marginBottom:8},input:{borderWidth:1,borderColor:"#ccc",borderRadius:12,padding:13},multi:{minHeight:90,textAlignVertical:"top"},wrap:{flexDirection:"row",flexWrap:"wrap",gap:8},chip:{borderWidth:1,borderColor:"#ccc",borderRadius:18,paddingHorizontal:12,paddingVertical:8},chipSelected:{borderWidth:2},row:{flexDirection:"row",gap:8},radius:{borderWidth:1,borderColor:"#ccc",borderRadius:10,padding:9},selected:{borderWidth:2},avail:{marginTop:18,paddingVertical:10,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},muted:{opacity:.6,fontSize:12},primary:{marginTop:14,borderWidth:1,borderRadius:12,padding:15,alignItems:"center"},secondary:{marginTop:14,borderWidth:1,borderRadius:12,padding:15,alignItems:"center"},buttonText:{fontWeight:"800"},note:{marginTop:18,opacity:.6,fontSize:12}});
