import { useState } from "react";
import { Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput } from "react-native";
import { VasudhaLogo } from "../src/components/VasudhaLogo";
import { useLocalSearchParams, router } from "expo-router";
import { supabase } from "../src/lib/supabase";
export default function Quote(){
 const {requestId}=useLocalSearchParams<{requestId:string}>();const [amount,setAmount]=useState("");const [message,setMessage]=useState("");const [duration,setDuration]=useState("");const [busy,setBusy]=useState(false);
 async function submit(){const n=Number(amount);if(!requestId||!Number.isFinite(n)||n<0){Alert.alert("Enter a valid amount");return;}setBusy(true);const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from("quotes").insert({request_id:requestId,professional_id:user?.id,amount_inr:n,message:message.trim()||null,estimated_duration:duration.trim()||null});setBusy(false);if(error)Alert.alert("Quotation failed",error.message);else{Alert.alert("Quotation sent","The customer can now compare and accept your quotation.");router.back();}}
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container} keyboardShouldPersistTaps="handled"><VasudhaLogo compact/><Text style={s.title}>Submit Quotation</Text><Text style={s.label}>Your price (₹)</Text><TextInput value={amount} onChangeText={setAmount} keyboardType="numeric" placeholder="1500" style={s.input}/><Text style={s.label}>Estimated duration</Text><TextInput value={duration} onChangeText={setDuration} placeholder="e.g. 2 hours" style={s.input}/><Text style={s.label}>Message</Text><TextInput value={message} onChangeText={setMessage} multiline placeholder="Explain what is included..." style={[s.input,s.large]}/><Pressable disabled={busy} onPress={submit} style={s.primary}><Text style={s.primaryText}>{busy?"Sending...":"Send Quotation"}</Text></Pressable></ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#fff"},container:{padding:20},title:{fontSize:28,fontWeight:"800"},label:{fontWeight:"800",marginTop:20,marginBottom:7},input:{borderWidth:1,borderColor:"#cfdad6",borderRadius:12,padding:12,minHeight:48,backgroundColor:"#fff"},large:{height:130,textAlignVertical:"top"},primary:{marginTop:24,borderRadius:12,padding:15,alignItems:"center",justifyContent:"center",minHeight:48,backgroundColor:"#087D65"},primaryText:{color:"#fff",fontWeight:"800"}});