import { useEffect,useState } from "react";
import { Alert,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View } from "react-native";
import { useLocalSearchParams,router } from "expo-router";
import { supabase } from "../src/lib/supabase";
export default function Quotes(){
 const {requestId}=useLocalSearchParams<{requestId:string}>();const [quotes,setQuotes]=useState<any[]>([]);const [request,setRequest]=useState<any>(null);const [busy,setBusy]=useState(false);
 useEffect(()=>{load();},[requestId]);
 async function load(){if(!requestId)return;const [{data:r,error:re},{data:q,error:qe}]=await Promise.all([supabase.from("service_requests").select("*").eq("id",requestId).maybeSingle(),supabase.from("quotes").select("*").eq("request_id",requestId).order("amount_inr",{ascending:true})]);if(re||qe)Alert.alert("Unable to load quotes",(re||qe)?.message||"Error");setRequest(r);setQuotes(q||[]);}
 async function accept(id:string){setBusy(true);const {error}=await supabase.rpc("accept_quote",{p_quote_id:id});if(error){setBusy(false);Alert.alert("Unable to accept",error.message);return;}const {data,error:e}=await supabase.rpc("create_job_from_quote",{p_quote_id:id});setBusy(false);if(e){Alert.alert("Job creation failed",e.message);return;}Alert.alert("Quote accepted","Your job has been created.");router.push({pathname:"/jobs"});}
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container}><Text style={s.title}>Compare Quotations</Text>{request?<View style={s.request}><Text style={s.name}>{request.title}</Text><Text style={s.desc}>{request.description}</Text></View>:null}{quotes.length===0?<Text style={s.muted}>No quotations yet.</Text>:quotes.map(q=><View key={q.id} style={s.card}><Text style={s.price}>₹{Number(q.amount_inr).toLocaleString("en-IN")}</Text><Text style={s.duration}>{q.estimated_duration||"Duration not specified"}</Text>{q.message?<Text style={s.desc}>{q.message}</Text>:null}<Text style={s.muted}>Submitted {new Date(q.created_at).toLocaleDateString()}</Text>{q.status==="submitted"&&request?.status==="requested"?<Pressable disabled={busy} onPress={()=>accept(q.id)} style={s.primary}><Text style={s.primaryText}>{busy?"Processing...":"Accept This Quote"}</Text></Pressable>:<Text style={s.status}>{q.status}</Text>}</View>)}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1},container:{padding:20,paddingBottom:50},title:{fontSize:28,fontWeight:"800"},request:{borderWidth:1,borderRadius:14,padding:15,marginTop:15},name:{fontSize:19,fontWeight:"800"},desc:{marginTop:7,opacity:.75},card:{borderWidth:1,borderRadius:16,padding:16,marginTop:14},price:{fontSize:24,fontWeight:"800"},duration:{marginTop:4},muted:{opacity:.6,marginTop:7},status:{fontWeight:"800",marginTop:10},primary:{marginTop:14,borderRadius:12,padding:14,alignItems:"center",backgroundColor:"#111"},primaryText:{color:"#fff",fontWeight:"800"}});