import { useState } from "react";
import { Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { useLocalSearchParams, router } from "expo-router";
import { supabase } from "../src/lib/supabase";

const fields=[["punctuality","Punctuality & Time"],["work_quality","Work Quality / Expertise"],["professional_behaviour","Professional Behaviour"],["communication","Communication"],["value_for_money","Price / Value for Money"],["reliability","Reliability"],["safety_care","Safety & Care"]];
export default function Review(){
 const {jobId,professionalId}=useLocalSearchParams<{jobId:string;professionalId:string}>(); const [scores,setScores]=useState<Record<string,number>>({}); const [again,setAgain]=useState(true); const [comment,setComment]=useState(""); const [busy,setBusy]=useState(false);
 async function submit(){if(!jobId||!professionalId||fields.some(([k])=>!scores[k])){Alert.alert("Complete review","Please rate every category.");return;}setBusy(true);const {data:{user}}=await supabase.auth.getUser();const payload:any={job_id:jobId,customer_id:user?.id,professional_id:professionalId,would_hire_again:again,comment:comment.trim()||null};fields.forEach(([k])=>payload[k]=scores[k]);const {error}=await supabase.from("job_reviews").insert(payload);if(!error)await supabase.rpc("recalculate_professional_trust",{p_professional_id:professionalId});setBusy(false);if(error)Alert.alert("Review failed",error.message);else{Alert.alert("Thank you","Your review has been submitted.");router.back();}}
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container}><Text style={s.title}>Rate Your Experience</Text><Text style={s.muted}>Your feedback helps VASUDHA CONNECT build trustworthy professionals.</Text>{fields.map(([key,label])=><View key={key} style={s.block}><Text style={s.label}>{label}</Text><View style={s.row}>{[1,2,3,4,5].map(n=><Pressable key={n} onPress={()=>setScores({...scores,[key]:n})} style={[s.star,scores[key]===n&&s.selected]}><Text style={scores[key]===n?s.white:s.dark}>{n}</Text></Pressable>)}</View></View>)}<Text style={s.label}>Would you hire again?</Text><View style={s.row}><Pressable onPress={()=>setAgain(true)} style={[s.choice,again&&s.selected]}><Text style={again?s.white:s.dark}>Yes</Text></Pressable><Pressable onPress={()=>setAgain(false)} style={[s.choice,!again&&s.selected]}><Text style={!again?s.white:s.dark}>No</Text></Pressable></View><Text style={s.label}>Comment (optional)</Text><TextInput value={comment} onChangeText={setComment} multiline placeholder="Tell us about the experience..." style={s.input}/><Pressable onPress={submit} disabled={busy} style={s.primary}><Text style={s.white}>{busy?"Submitting...":"Submit Review"}</Text></Pressable></ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1},container:{padding:20,paddingBottom:50},title:{fontSize:28,fontWeight:"800"},muted:{opacity:.65,marginTop:6},block:{marginTop:18},label:{fontWeight:"800",marginBottom:8},row:{flexDirection:"row",gap:8},star:{width:40,height:40,borderWidth:1,borderRadius:10,alignItems:"center",justifyContent:"center"},selected:{backgroundColor:"#111"},white:{color:"#fff",fontWeight:"800"},dark:{color:"#111"},choice:{borderWidth:1,borderRadius:10,paddingHorizontal:22,paddingVertical:10},input:{borderWidth:1,borderRadius:12,padding:12,height:110,textAlignVertical:"top"},primary:{marginTop:24,borderRadius:12,padding:15,alignItems:"center",backgroundColor:"#111"}});
