import { useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { VasudhaLogo } from "../src/components/VasudhaLogo";
import { useLocalSearchParams, router } from "expo-router";
import { supabase } from "../src/lib/supabase";
import { KAMPRO } from "../src/components/kamproTheme";

const fields=[["punctuality","Punctuality & Time"],["work_quality","Work Quality / Expertise"],["professional_behaviour","Professional Behaviour"],["communication","Communication"],["value_for_money","Price / Value for Money"],["reliability","Reliability"],["safety_care","Safety & Care"]];
export default function Review(){
 const {jobId,professionalId}=useLocalSearchParams<{jobId:string;professionalId:string}>(); const [scores,setScores]=useState<Record<string,number>>({}); const [again,setAgain]=useState(true); const [comment,setComment]=useState(""); const [busy,setBusy]=useState(false);
 async function submit(){if(!jobId||!professionalId||fields.some(([k])=>!scores[k])){Alert.alert("Complete review","Please rate every category.");return;}setBusy(true);const {data:{user}}=await supabase.auth.getUser();const payload:any={job_id:jobId,customer_id:user?.id,professional_id:professionalId,would_hire_again:again,comment:comment.trim()||null};fields.forEach(([k])=>payload[k]=scores[k]);const {error}=await supabase.from("job_reviews").insert(payload);setBusy(false);if(error)Alert.alert("Review failed",error.message);else{Alert.alert("Review submitted","Your review has been submitted successfully.",[{text:"OK",onPress:()=>router.back()}]);}}
 return <SafeAreaView style={s.safe} edges={["top"]}><ScrollView contentContainerStyle={s.container} keyboardShouldPersistTaps="handled"><VasudhaLogo compact/><Text style={s.title}>Rate Your Experience</Text><Text style={s.muted}>Your feedback helps KAMPRO build trustworthy professionals.</Text>{fields.map(([key,label])=><View key={key} style={s.block}><Text style={s.label}>{label}</Text><View style={s.row}>{[1,2,3,4,5].map(n=><Pressable key={n} onPress={()=>setScores({...scores,[key]:n})} style={[s.star,scores[key]===n&&s.selected]}><Text style={scores[key]===n?s.starGlyph:s.starOff}>★</Text></Pressable>)}</View></View>)}<Text style={s.label}>Would you hire again?</Text><View style={s.row}><Pressable onPress={()=>setAgain(true)} style={[s.choice,again&&s.selected]}><Text style={again?s.white:s.dark}>Yes</Text></Pressable><Pressable onPress={()=>setAgain(false)} style={[s.choice,!again&&s.selected]}><Text style={!again?s.white:s.dark}>No</Text></Pressable></View><Text style={s.label}>Comment (optional)</Text><TextInput value={comment} onChangeText={setComment} multiline placeholder="Tell us about the experience..." style={s.input}/><Pressable onPress={submit} disabled={busy} style={s.primary}><Text style={s.white}>{busy?"Submitting...":"Submit Review"}</Text></Pressable><Pressable onPress={()=>router.back()} disabled={busy} style={s.skip}><Text style={s.skipText}>Skip Review</Text></Pressable></ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:KAMPRO.background},container:{width:"100%",maxWidth:720,alignSelf:"center",padding:28,paddingBottom:60},title:{fontSize:30,fontWeight:"900",color:KAMPRO.navy},muted:{color:KAMPRO.muted,marginTop:6},block:{marginTop:18},label:{fontWeight:"800",color:KAMPRO.ink,marginBottom:8},row:{flexDirection:"row",gap:8},star:{width:40,height:40,borderWidth:1,borderRadius:10,alignItems:"center",justifyContent:"center"},selected:{backgroundColor:"#FF4B1F"},white:{color:"#fff",fontWeight:"800"},dark:{color:"#111"},starGlyph:{color:"#fff",fontSize:18},starOff:{color:"#f0a400",fontSize:18},choice:{borderWidth:1,borderRadius:10,paddingHorizontal:22,paddingVertical:10},input:{borderWidth:1,borderRadius:12,padding:12,height:110,textAlignVertical:"top",color:KAMPRO.ink},primary:{marginTop:28,borderRadius:14,padding:15,alignItems:"center",backgroundColor:KAMPRO.brand,minHeight:52,justifyContent:"center"},skip:{marginTop:10,borderWidth:1,borderColor:"#CBD0D8",borderRadius:14,padding:15,alignItems:"center",justifyContent:"center",minHeight:48},skipText:{color:"#596575",fontWeight:"800"}});
