create or replace function public.admin_professional_360(p_user_id uuid)
returns jsonb
language plpgsql
security definer
set search_path=public
as $function$
declare v_result jsonb;
begin
  if not public.is_admin() then raise exception 'Admin access required'; end if;
  if p_user_id is null then raise exception 'Professional is required'; end if;
  select jsonb_build_object(
    'profile',(select to_jsonb(p) from (select pr.id,pr.full_name,pr.display_name,pr.avatar_url,pr.bio,pr.city,pr.state,pr.country,pr.current_mode,pr.account_status,pr.created_at,pr.updated_at from public.profiles pr where pr.id=p_user_id) p),
    'professional',(select to_jsonb(pp) from (select pp.headline,pp.about,pp.years_experience,pp.verification_status,pp.is_available,pp.service_radius_km,pp.base_latitude,pp.base_longitude,pp.response_rate,pp.completion_rate,pp.cancellation_rate,pp.trust_score,pp.created_at,pp.updated_at from public.professional_profiles pp where pp.user_id=p_user_id) pp),
    'services',coalesce((select jsonb_agg(to_jsonb(x) order by x.is_primary desc,x.service_name,x.sub_service_name) from (select pss.sub_service_id,pss.years_experience,pss.is_primary,ss.name sub_service_name,ss.status sub_service_status,s.id service_id,s.name service_name,s.status service_status from public.professional_sub_services pss join public.service_catalogue_sub_services ss on ss.id=pss.sub_service_id join public.service_catalogue_services s on s.id=ss.service_id where pss.professional_id=p_user_id) x),'[]'::jsonb),
    'areas',coalesce((select jsonb_agg(to_jsonb(a) order by a.is_primary desc,a.label) from public.service_areas a where a.professional_id=p_user_id),'[]'::jsonb),
    'verification',coalesce((select jsonb_agg(to_jsonb(v) order by v.submitted_at desc) from (select vd.id,vd.document_type,vd.status,vd.reviewer_note,vd.submitted_at,vd.reviewed_at from public.verification_documents vd where vd.professional_id=p_user_id) v),'[]'::jsonb),
    'connections',jsonb_build_object('total',(select count(*) from public.professional_connections c where c.professional_id=p_user_id),'active',(select count(*) from public.professional_connections c where c.professional_id=p_user_id and c.expires_at>now()),'recent',coalesce((select jsonb_agg(to_jsonb(c) order by c.purchased_at desc) from (select pc.id,pc.customer_id,coalesce(pr.display_name,pr.full_name,'Customer') customer_name,pc.purchased_at,pc.expires_at,pc.last_accessed_at from public.professional_connections pc left join public.profiles pr on pr.id=pc.customer_id where pc.professional_id=p_user_id order by pc.purchased_at desc limit 10)c),'[]'::jsonb)),
    'work',jsonb_build_object('requests_total',(select count(*) from public.service_requests r where r.professional_id=p_user_id),'jobs_total',(select count(*) from public.jobs j where j.professional_id=p_user_id),'jobs_completed',(select count(*) from public.jobs j where j.professional_id=p_user_id and j.status='customer_confirmed'),'jobs_cancelled',(select count(*) from public.jobs j where j.professional_id=p_user_id and j.status='cancelled'),'recent_jobs',coalesce((select jsonb_agg(to_jsonb(jx) order by jx.created_at desc) from (select j.id,j.title,j.status,j.agreed_amount_inr,j.created_at,j.updated_at,coalesce(pr.display_name,pr.full_name,'Customer') customer_name from public.jobs j left join public.profiles pr on pr.id=j.customer_id where j.professional_id=p_user_id order by j.created_at desc limit 10)jx),'[]'::jsonb),'recent_requests',coalesce((select jsonb_agg(to_jsonb(rx) order by rx.created_at desc) from (select r.id,r.title,r.status,r.preferred_date,r.preferred_time,r.budget_min_inr,r.budget_max_inr,r.created_at,coalesce(pr.display_name,pr.full_name,'Customer') customer_name from public.service_requests r left join public.profiles pr on pr.id=r.customer_id where r.professional_id=p_user_id order by r.created_at desc limit 10)rx),'[]'::jsonb)),
    'reputation',jsonb_build_object('reviews_total',(select count(*) from public.job_reviews jr where jr.professional_id=p_user_id),'average_score',coalesce((select round(avg((jr.punctuality+jr.work_quality+jr.professional_behaviour+jr.communication+jr.value_for_money+jr.reliability+jr.safety_care)::numeric/7),2) from public.job_reviews jr where jr.professional_id=p_user_id),0),'would_hire_again_pct',coalesce((select round(100*avg(case when jr.would_hire_again then 1.0 else 0.0 end),1) from public.job_reviews jr where jr.professional_id=p_user_id),0)),
    'portfolio',jsonb_build_object('total',(select count(*) from public.portfolio_items pi where pi.professional_id=p_user_id),'approved',(select count(*) from public.portfolio_items pi where pi.professional_id=p_user_id and pi.moderation_status='approved'),'pending',(select count(*) from public.portfolio_items pi where pi.professional_id=p_user_id and pi.moderation_status='pending')),
    'complaints',jsonb_build_object('total',(select count(*) from public.complaints c where c.against_user_id=p_user_id),'open',(select count(*) from public.complaints c where c.against_user_id=p_user_id and c.status in ('open','under_review')),'recent',coalesce((select jsonb_agg(to_jsonb(cx) order by cx.created_at desc) from (select c.id,c.job_id,c.category,c.status,c.description,c.admin_note,c.created_at,c.updated_at,coalesce(pr.display_name,pr.full_name,'User') reporter_name from public.complaints c left join public.profiles pr on pr.id=c.reporter_id where c.against_user_id=p_user_id order by c.created_at desc limit 10)cx),'[]'::jsonb))
  ) into v_result;
  if v_result->'profile' is null and v_result->'professional' is null then raise exception 'Professional not found'; end if;
  return v_result;
end;
$function$;
revoke all on function public.admin_professional_360(uuid) from public,anon,authenticated;
grant execute on function public.admin_professional_360(uuid) to authenticated;